# GoReleaser configuration for DuraGraph
# https://goreleaser.com

version: 2

before:
  hooks:
    # Run tests before building
    - go test ./... -short
    - go mod tidy

builds:
  - id: duragraph-server
    binary: duragraph
    main: ./cmd/server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser
    flags:
      - -trimpath

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: "Performance Improvements"
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 2
    - title: "Documentation"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 3
    - title: Others
      order: 999
  filters:
    exclude:
      - "^chore"
      - "^test"
      - "^ci"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: duragraph
    name: duragraph
  draft: false
  prerelease: auto
  mode: append
  header: |
    ## DuraGraph {{ .Tag }}

    **Release Date**: {{ .Date }}

    ### Installation

    Download the binary for your platform from the assets below, or use Docker:

    ```bash
    # Docker Hub
    docker pull duragraph/api:{{ .Tag }}

    # GitHub Container Registry
    docker pull ghcr.io/duragraph/duragraph/api:{{ .Tag }}
    ```

    ### Binary Installation

    ```bash
    # Linux/macOS
    curl -sL https://github.com/duragraph/duragraph/releases/download/{{ .Tag }}/duragraph_Linux_x86_64.tar.gz | tar xz
    sudo mv duragraph /usr/local/bin/

    # Or with script
    curl -sL https://raw.githubusercontent.com/duragraph/duragraph/main/install.sh | bash
    ```

  footer: |
    ---

    **Full Changelog**: https://github.com/duragraph/duragraph/compare/{{ .PreviousTag }}...{{ .Tag }}

    ### Resources
    - 📚 [Documentation](https://duragraph.dev/docs)
    - 🐳 [Docker Hub](https://hub.docker.com/r/duragraph/api)
    - 💬 [Discussions](https://github.com/duragraph/duragraph/discussions)
    - 🐛 [Report Issues](https://github.com/duragraph/duragraph/issues)

# Docker images (built and pushed by GoReleaser)
dockers:
  - id: api-amd64
    use: buildx
    goos: linux
    goarch: amd64
    dockerfile: deploy/docker/Dockerfile.server
    image_templates:
      - "duragraph/api:{{ .Tag }}-amd64"
      - "duragraph/api:latest-amd64"
      - "ghcr.io/duragraph/duragraph/api:{{ .Tag }}-amd64"
      - "ghcr.io/duragraph/duragraph/api:latest-amd64"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"

  - id: api-arm64
    use: buildx
    goos: linux
    goarch: arm64
    dockerfile: deploy/docker/Dockerfile.server
    image_templates:
      - "duragraph/api:{{ .Tag }}-arm64"
      - "duragraph/api:latest-arm64"
      - "ghcr.io/duragraph/duragraph/api:{{ .Tag }}-arm64"
      - "ghcr.io/duragraph/duragraph/api:latest-arm64"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: duragraph/api:{{ .Tag }}
    image_templates:
      - duragraph/api:{{ .Tag }}-amd64
      - duragraph/api:{{ .Tag }}-arm64

  - name_template: duragraph/api:latest
    image_templates:
      - duragraph/api:latest-amd64
      - duragraph/api:latest-arm64

  - name_template: ghcr.io/duragraph/duragraph/api:{{ .Tag }}
    image_templates:
      - ghcr.io/duragraph/duragraph/api:{{ .Tag }}-amd64
      - ghcr.io/duragraph/duragraph/api:{{ .Tag }}-arm64

  - name_template: ghcr.io/duragraph/duragraph/api:latest
    image_templates:
      - ghcr.io/duragraph/duragraph/api:latest-amd64
      - ghcr.io/duragraph/duragraph/api:latest-arm64

# Homebrew tap (optional - for easy installation on macOS)
brews:
  - repository:
      owner: duragraph
      name: homebrew-tap
    directory: Formula
    homepage: https://duragraph.dev
    description: Self-hosted LangGraph Cloud-compatible API
    license: Apache-2.0
    install: |
      bin.install "duragraph"
    test: |
      system "#{bin}/duragraph", "version"

# Snapcraft (optional - for easy installation on Linux)
# snapcrafts:
#   - name: duragraph
#     summary: Self-hosted LangGraph Cloud-compatible API
#     description: |
#       DuraGraph provides a LangGraph Cloud-compatible API built with
#       Event Sourcing and CQRS patterns for reliable AI workflow orchestration.
#     grade: stable
#     confinement: strict
#     publish: true

announce:
  skip: false
