// Code generated by tygo. DO NOT EDIT.
// ⚠ Generated by tygo from internal/infrastructure/http/dto.
// Do not edit by hand. Run `task gen:types` after changing DTOs.

//////////
// source: cron.go

/**
 * CreateCronRequest represents the request to create a cron job.
 */
export interface CreateCronRequest {
  assistant_id: string;
  schedule: string;
  input?: { [key: string]: any};
  metadata?: { [key: string]: any};
  config?: { [key: string]: any};
  context?: { [key: string]: any};
  webhook?: string;
  multitask_strategy?: string;
  on_run_completed?: string;
  end_time?: string /* RFC3339 timestamp */;
  enabled?: boolean;
  timezone?: string;
  interrupt_before?: string[];
  interrupt_after?: string[];
}
/**
 * UpdateCronRequest represents the request to update a cron job.
 */
export interface UpdateCronRequest {
  schedule?: string;
  input?: { [key: string]: any};
  metadata?: { [key: string]: any};
  config?: { [key: string]: any};
  context?: { [key: string]: any};
  webhook?: string;
  on_run_completed?: string;
  end_time?: string /* RFC3339 timestamp */;
  enabled?: boolean;
  timezone?: string;
  interrupt_before?: string[];
  interrupt_after?: string[];
}
/**
 * SearchCronsRequest represents the request to search cron jobs.
 */
export interface SearchCronsRequest {
  assistant_id?: string;
  thread_id?: string;
  enabled?: boolean;
  limit?: number /* int */;
  offset?: number /* int */;
  sort_by?: string;
  sort_order?: string;
}
/**
 * CountCronsRequest represents the request to count cron jobs.
 */
export interface CountCronsRequest {
  assistant_id?: string;
  thread_id?: string;
}
/**
 * CronResponse represents a cron job in API responses.
 */
export interface CronResponse {
  cron_id: string;
  assistant_id: string;
  thread_id?: string;
  schedule: string;
  timezone: string;
  payload: { [key: string]: any};
  metadata: { [key: string]: any};
  enabled: boolean;
  on_run_completed: string;
  end_time?: string /* RFC3339 timestamp */;
  next_run_date?: string /* RFC3339 timestamp */;
  user_id?: string;
  created_at: string /* RFC3339 timestamp */;
  updated_at: string /* RFC3339 timestamp */;
}

//////////
// source: langgraph.go

/**
 * StringOrSlice is a type that can unmarshal from either a string or []string
 * This is needed for LangGraph SDK compatibility which sends stream_mode as a string
 */
export type StringOrSlice = string[];
/**
 * CreateRunRequest represents the request to create a run
 */
export interface CreateRunRequest {
  assistant_id: string;
  thread_id?: string;
  input?: { [key: string]: any};
  metadata?: { [key: string]: any};
  config?: { [key: string]: any};
  kwargs?: { [key: string]: any};
  stream_mode?: StringOrSlice; // Can be string or []string
  stream_subgraphs?: boolean; // LangGraph SDK sends this
  stream_resumable?: boolean; // LangGraph SDK sends this
  on_completion?: string;
  interrupt_before?: string[]; // Node IDs to interrupt before execution
  interrupt_after?: string[]; // Node IDs to interrupt after execution
  webhook?: string; // Webhook URL for completion notification
  multitask_strategy?: string; // Strategy for concurrent runs: reject, interrupt, rollback, enqueue
}
/**
 * CreateRunResponse represents the response from creating a run
 */
export interface CreateRunResponse {
  run_id: string;
  thread_id: string;
  assistant_id: string;
  status: string;
  metadata?: { [key: string]: any};
  kwargs?: { [key: string]: any};
  created_at: string /* RFC3339 timestamp */;
}
/**
 * GetRunResponse represents the response from getting a run
 */
export interface GetRunResponse {
  run_id: string;
  thread_id: string;
  assistant_id: string;
  status: string;
  input?: { [key: string]: any};
  output?: { [key: string]: any};
  error?: string;
  metadata?: { [key: string]: any};
  config?: { [key: string]: any};
  kwargs?: { [key: string]: any};
  multitask_strategy?: string;
  created_at: string /* RFC3339 timestamp */;
  started_at?: string /* RFC3339 timestamp */;
  completed_at?: string /* RFC3339 timestamp */;
  updated_at: string /* RFC3339 timestamp */;
}
/**
 * SubmitToolOutputsRequest represents the request to submit tool outputs
 */
export interface SubmitToolOutputsRequest {
  tool_outputs: ToolOutput[];
}
/**
 * ToolOutput represents a tool output
 */
export interface ToolOutput {
  tool_call_id: string;
  output: string;
}
/**
 * CreateAssistantRequest represents the request to create an assistant
 */
export interface CreateAssistantRequest {
  graph_id?: string;
  name: string;
  description?: string;
  model?: string;
  instructions?: string;
  tools?: { [key: string]: any}[];
  metadata?: { [key: string]: any};
  config?: { [key: string]: any};
  context?: { [key: string]: any}[];
}
/**
 * CreateAssistantResponse represents the response from creating an assistant.
 * `graph_id` echoes the request so clients (dashboard, SDKs) can confirm
 * the assistant was bound to the expected registered graph without
 * re-fetching via GET.
 */
export interface CreateAssistantResponse {
  assistant_id: string;
  graph_id?: string;
  name: string;
  description?: string;
  model?: string;
  instructions?: string;
  tools?: { [key: string]: any}[];
  created_at: string /* RFC3339 timestamp */;
}
/**
 * CreateThreadRequest represents the request to create a thread
 */
export interface CreateThreadRequest {
  metadata?: { [key: string]: any};
}
/**
 * CreateThreadResponse represents the response from creating a thread
 */
export interface CreateThreadResponse {
  thread_id: string;
  metadata?: { [key: string]: any};
  created_at: string /* RFC3339 timestamp */;
}
/**
 * ErrorResponse represents an error response
 */
export interface ErrorResponse {
  error: string;
  message: string;
  code?: string;
  request_id?: string;
}
/**
 * UpdateAssistantRequest represents the request to update an assistant
 */
export interface UpdateAssistantRequest {
  name?: string;
  description?: string;
  model?: string;
  instructions?: string;
  tools?: { [key: string]: any}[];
}
/**
 * AssistantResponse represents an assistant resource (LangGraph compatible)
 */
export interface AssistantResponse {
  assistant_id: string;
  graph_id: string;
  name: string;
  description?: string;
  model?: string;
  instructions?: string;
  tools?: { [key: string]: any}[];
  metadata: { [key: string]: any};
  config?: { [key: string]: any};
  context?: { [key: string]: any}[];
  version: number /* int */;
  created_at: string;
  updated_at: string;
}
/**
 * ListAssistantsResponse represents the response from listing assistants
 */
export interface ListAssistantsResponse {
  assistants: AssistantResponse[];
  total: number /* int */;
}
/**
 * UpdateThreadRequest represents the request to update a thread
 */
export interface UpdateThreadRequest {
  metadata?: { [key: string]: any};
}
/**
 * ThreadResponse represents a thread resource (LangGraph compatible)
 */
export interface ThreadResponse {
  thread_id: string;
  status: string;
  values: { [key: string]: any};
  metadata?: { [key: string]: any};
  config?: { [key: string]: any};
  interrupts?: { [key: string]: any}[];
  created_at: string;
  updated_at: string;
}
/**
 * MessageResponse represents a message in a thread
 */
export interface MessageResponse {
  id: string;
  role: string;
  content: string;
  metadata?: { [key: string]: any};
  created_at: number /* int64 */;
}
/**
 * ListThreadsResponse represents the response from listing threads
 */
export interface ListThreadsResponse {
  threads: ThreadResponse[];
  total: number /* int */;
}
/**
 * AddMessageRequest represents the request to add a message
 */
export interface AddMessageRequest {
  role: string;
  content: string;
  metadata?: { [key: string]: any};
}
/**
 * SearchAssistantsRequest represents the request to search assistants
 */
export interface SearchAssistantsRequest {
  graph_id?: string;
  metadata?: { [key: string]: any};
  limit?: number /* int */;
  offset?: number /* int */;
}
/**
 * CountAssistantsRequest represents the request to count assistants
 */
export interface CountAssistantsRequest {
  graph_id?: string;
  metadata?: { [key: string]: any};
}
/**
 * SearchThreadsRequest represents the request to search threads
 */
export interface SearchThreadsRequest {
  status?: string;
  metadata?: { [key: string]: any};
  limit?: number /* int */;
  offset?: number /* int */;
}
/**
 * CountThreadsRequest represents the request to count threads
 */
export interface CountThreadsRequest {
  status?: string;
  metadata?: { [key: string]: any};
}
/**
 * CountResponse represents a count response
 */
export interface CountResponse {
  count: number /* int */;
}
/**
 * ThreadStateResponse represents the current state of a thread
 */
export interface ThreadStateResponse {
  values: { [key: string]: any};
  next: string[];
  tasks?: { [key: string]: any}[];
  metadata?: { [key: string]: any};
  created_at: number /* int64 */;
  checkpoint_id?: string;
  checkpoint_ns?: string;
  parent_config?: { [key: string]: any};
}
/**
 * UpdateThreadStateRequest represents the request to update thread state
 */
export interface UpdateThreadStateRequest {
  values: { [key: string]: any};
  as_node?: string;
  checkpoint_ns?: string;
}
/**
 * ThreadHistoryEntry represents a single entry in thread history
 */
export interface ThreadHistoryEntry {
  checkpoint_id: string;
  parent_checkpoint_id?: string;
  values: { [key: string]: any};
  metadata?: { [key: string]: any};
  created_at: number /* int64 */;
}
/**
 * GetThreadHistoryRequest represents the request to get thread history
 */
export interface GetThreadHistoryRequest {
  checkpoint_ns?: string;
  limit?: number /* int */;
  before?: string;
}
/**
 * CopyThreadRequest represents the request to copy a thread
 */
export interface CopyThreadRequest {
  checkpoint_id?: string;
}
/**
 * CopyThreadResponse represents the response from copying a thread
 */
export interface CopyThreadResponse {
  thread_id: string;
}
/**
 * AssistantVersionResponse represents a version of an assistant
 */
export interface AssistantVersionResponse {
  id: string;
  assistant_id: string;
  version: number /* int */;
  graph_id?: string;
  config: { [key: string]: any};
  context?: any[];
  created_at: number /* int64 */;
}
/**
 * CreateAssistantVersionRequest represents the request to create a new version
 */
export interface CreateAssistantVersionRequest {
  graph_id?: string;
  config?: { [key: string]: any};
  context?: any[];
}
/**
 * SetLatestVersionRequest represents the request to set the latest version
 */
export interface SetLatestVersionRequest {
  version: number /* int */;
}
/**
 * AssistantSchemaResponse represents the schema of an assistant
 */
export interface AssistantSchemaResponse {
  graph_id?: string;
  input_schema: { [key: string]: any};
  output_schema: { [key: string]: any};
  state_schema: { [key: string]: any};
  config_schema: { [key: string]: any};
}
/**
 * ResumeRunRequest represents a LangGraph-compatible resume request
 * This supports the Command pattern for human-in-the-loop workflows
 */
export interface ResumeRunRequest {
  /**
   * Input to resume with (replaces pending task input)
   */
  input?: { [key: string]: any};
  /**
   * Command to execute when resuming
   */
  command?: Command;
  /**
   * Config overrides for the resumed run
   */
  config?: { [key: string]: any};
}
/**
 * Command represents a LangGraph Command object for resuming with specific actions
 */
export interface Command {
  /**
   * Resume value - the value to resume with (for interrupt_before/after)
   */
  resume?: any;
  /**
   * Update state values before resuming
   */
  update?: { [key: string]: any};
  /**
   * Send messages/values to specific nodes
   */
  send?: SendMessage[];
  /**
   * Goto a specific node (skip current)
   */
  goto?: string;
}
/**
 * SendMessage represents a message to send to a specific node
 */
export interface SendMessage {
  node: string;
  message: any;
}
/**
 * InterruptResponse represents the response when a run is interrupted
 */
export interface InterruptResponse {
  run_id: string;
  thread_id: string;
  status: string;
  interrupt_type?: string; // "before" or "after"
  node_id?: string;
  reason?: string;
  state?: { [key: string]: any};
  tool_calls?: { [key: string]: any}[];
}
/**
 * GraphNodeResponse represents a node in a graph
 */
export interface GraphNodeResponse {
  id: string;
  type: string;
  data?: { [key: string]: any};
  metadata?: { [key: string]: number /* float64 */};
}
/**
 * GraphEdgeResponse represents an edge in a graph
 */
export interface GraphEdgeResponse {
  id?: string;
  source: string;
  target: string;
  data?: { [key: string]: any};
}
/**
 * GraphResponse represents the graph structure for an assistant
 */
export interface GraphResponse {
  nodes: GraphNodeResponse[];
  edges: GraphEdgeResponse[];
  config?: { [key: string]: any};
}
/**
 * SubgraphInfoResponse represents information about a subgraph
 */
export interface SubgraphInfoResponse {
  namespace: string;
  graph_id?: string;
}

//////////
// source: store.go

/**
 * PutStoreItemRequest represents the request to store an item.
 */
export interface PutStoreItemRequest {
  namespace: string[];
  key: string;
  value: { [key: string]: any};
  ttl?: number /* int */;
}
/**
 * GetStoreItemRequest represents query params for retrieving an item.
 */
export interface GetStoreItemRequest {
  Namespace: string;
  Key: string;
  RefreshTTL: boolean;
}
/**
 * DeleteStoreItemRequest represents the request to delete an item.
 */
export interface DeleteStoreItemRequest {
  namespace: string[];
  key: string;
}
/**
 * SearchStoreItemsRequest represents the request to search items.
 */
export interface SearchStoreItemsRequest {
  namespace_prefix: string[];
  filter?: { [key: string]: any};
  limit?: number /* int */;
  offset?: number /* int */;
  query?: string;
  refresh_ttl?: boolean;
}
/**
 * ListNamespacesRequest represents the request to list namespaces.
 */
export interface ListNamespacesRequest {
  prefix?: string[];
  suffix?: string[];
  max_depth?: number /* int */;
  limit?: number /* int */;
  offset?: number /* int */;
}
/**
 * StoreItemResponse represents a stored item in responses.
 */
export interface StoreItemResponse {
  namespace: string[];
  key: string;
  value: { [key: string]: any};
  created_at: string /* RFC3339 timestamp */;
  updated_at: string /* RFC3339 timestamp */;
}
/**
 * SearchStoreItemsResponse represents the response from searching items.
 */
export interface SearchStoreItemsResponse {
  items: StoreItemResponse[];
}

//////////
// source: worker.go

/**
 * RegisterWorkerRequest represents the request to register a worker
 */
export interface RegisterWorkerRequest {
  worker_id: string;
  name: string;
  capabilities: WorkerCapabilities;
  graph_definitions?: GraphDefinition[];
}
/**
 * WorkerCapabilities represents what a worker can do
 */
export interface WorkerCapabilities {
  graphs: string[];
  max_concurrent_runs: number /* int */;
}
/**
 * GraphDefinition represents a graph that a worker can execute
 */
export interface GraphDefinition {
  graph_id: string;
  name: string;
  description: string;
  nodes: NodeDefinition[];
  edges: EdgeDefinition[];
  entry_point: string;
}
/**
 * NodeDefinition represents a node in a graph
 */
export interface NodeDefinition {
  id: string;
  type: string;
  config?: { [key: string]: any};
}
/**
 * EdgeDefinition represents an edge in a graph
 */
export interface EdgeDefinition {
  source: string;
  target: string;
  condition?: string;
}
/**
 * RegisterWorkerResponse represents the response from registering a worker
 */
export interface RegisterWorkerResponse {
  worker_id: string;
  registered: boolean;
  heartbeat_url: string;
  poll_url: string;
  deregister_url: string;
  event_stream_url: string;
}
/**
 * HeartbeatRequest represents the request to send a heartbeat
 */
export interface HeartbeatRequest {
  status: string;
  active_runs: number /* int */;
  total_runs: number /* int */;
  failed_runs: number /* int */;
}
/**
 * HeartbeatResponse represents the response from a heartbeat
 */
export interface HeartbeatResponse {
  acknowledged: boolean;
}
/**
 * PollRequest represents the request to poll for work
 */
export interface PollRequest {
  max_tasks?: number /* int */;
}
/**
 * PollResponse represents the response from polling for work
 */
export interface PollResponse {
  tasks: WorkerTask[];
}
/**
 * WorkerTask represents a task assigned to a worker
 */
export interface WorkerTask {
  task_id: string;
  run_id: string;
  thread_id: string;
  assistant_id: string;
  graph_id: string;
  input: { [key: string]: any};
  config?: { [key: string]: any};
  checkpoint?: { [key: string]: any};
  created_at: string /* RFC3339 timestamp */;
}
/**
 * DeregisterWorkerResponse represents the response from deregistering a worker
 */
export interface DeregisterWorkerResponse {
  worker_id: string;
  deregistered: boolean;
}
/**
 * WorkerStatusResponse represents the status of a worker
 */
export interface WorkerStatusResponse {
  worker_id: string;
  name: string;
  status: string;
  active_runs: number /* int */;
  total_runs: number /* int */;
  failed_runs: number /* int */;
  last_heartbeat: string /* RFC3339 timestamp */;
  registered_at: string /* RFC3339 timestamp */;
  graphs: string[];
}
/**
 * ListWorkersResponse represents the response from listing workers
 */
export interface ListWorkersResponse {
  workers: WorkerStatusResponse[];
  total: number /* int */;
}
/**
 * WorkerEventRequest represents an event sent from a worker
 */
export interface WorkerEventRequest {
  run_id: string;
  event_type: string;
  node_id?: string;
  data?: { [key: string]: any};
  timestamp: string /* RFC3339 timestamp */;
}
/**
 * WorkerEventResponse represents the response from sending an event
 */
export interface WorkerEventResponse {
  received: boolean;
}
