/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppTracesRouteImport } from './routes/_app/traces'
import { Route as AppThreadsRouteImport } from './routes/_app/threads'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppRunsRouteImport } from './routes/_app/runs'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppCostsRouteImport } from './routes/_app/costs'
import { Route as AppAssistantsRouteImport } from './routes/_app/assistants'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppTracesTraceIdRouteImport } from './routes/_app/traces/$traceId'
import { Route as AppThreadsThreadIdRouteImport } from './routes/_app/threads/$threadId'
import { Route as AppRunsRunIdRouteImport } from './routes/_app/runs/$runId'
import { Route as AppAssistantsAssistantIdRouteImport } from './routes/_app/assistants/$assistantId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTracesRoute = AppTracesRouteImport.update({
  id: '/traces',
  path: '/traces',
  getParentRoute: () => AppRoute,
} as any)
const AppThreadsRoute = AppThreadsRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRunsRoute = AppRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppCostsRoute = AppCostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantsRoute = AppAssistantsRouteImport.update({
  id: '/assistants',
  path: '/assistants',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppTracesTraceIdRoute = AppTracesTraceIdRouteImport.update({
  id: '/$traceId',
  path: '/$traceId',
  getParentRoute: () => AppTracesRoute,
} as any)
const AppThreadsThreadIdRoute = AppThreadsThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => AppThreadsRoute,
} as any)
const AppRunsRunIdRoute = AppRunsRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => AppRunsRoute,
} as any)
const AppAssistantsAssistantIdRoute =
  AppAssistantsAssistantIdRouteImport.update({
    id: '/$assistantId',
    path: '/$assistantId',
    getParentRoute: () => AppAssistantsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/analytics': typeof AppAnalyticsRoute
  '/assistants': typeof AppAssistantsRouteWithChildren
  '/costs': typeof AppCostsRoute
  '/profile': typeof AppProfileRoute
  '/runs': typeof AppRunsRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/threads': typeof AppThreadsRouteWithChildren
  '/traces': typeof AppTracesRouteWithChildren
  '/': typeof AppIndexRoute
  '/assistants/$assistantId': typeof AppAssistantsAssistantIdRoute
  '/runs/$runId': typeof AppRunsRunIdRoute
  '/threads/$threadId': typeof AppThreadsThreadIdRoute
  '/traces/$traceId': typeof AppTracesTraceIdRoute
}
export interface FileRoutesByTo {
  '/analytics': typeof AppAnalyticsRoute
  '/assistants': typeof AppAssistantsRouteWithChildren
  '/costs': typeof AppCostsRoute
  '/profile': typeof AppProfileRoute
  '/runs': typeof AppRunsRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/threads': typeof AppThreadsRouteWithChildren
  '/traces': typeof AppTracesRouteWithChildren
  '/': typeof AppIndexRoute
  '/assistants/$assistantId': typeof AppAssistantsAssistantIdRoute
  '/runs/$runId': typeof AppRunsRunIdRoute
  '/threads/$threadId': typeof AppThreadsThreadIdRoute
  '/traces/$traceId': typeof AppTracesTraceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/assistants': typeof AppAssistantsRouteWithChildren
  '/_app/costs': typeof AppCostsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/runs': typeof AppRunsRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/threads': typeof AppThreadsRouteWithChildren
  '/_app/traces': typeof AppTracesRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/assistants/$assistantId': typeof AppAssistantsAssistantIdRoute
  '/_app/runs/$runId': typeof AppRunsRunIdRoute
  '/_app/threads/$threadId': typeof AppThreadsThreadIdRoute
  '/_app/traces/$traceId': typeof AppTracesTraceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/analytics'
    | '/assistants'
    | '/costs'
    | '/profile'
    | '/runs'
    | '/settings'
    | '/threads'
    | '/traces'
    | '/'
    | '/assistants/$assistantId'
    | '/runs/$runId'
    | '/threads/$threadId'
    | '/traces/$traceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/analytics'
    | '/assistants'
    | '/costs'
    | '/profile'
    | '/runs'
    | '/settings'
    | '/threads'
    | '/traces'
    | '/'
    | '/assistants/$assistantId'
    | '/runs/$runId'
    | '/threads/$threadId'
    | '/traces/$traceId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/analytics'
    | '/_app/assistants'
    | '/_app/costs'
    | '/_app/profile'
    | '/_app/runs'
    | '/_app/settings'
    | '/_app/threads'
    | '/_app/traces'
    | '/_app/'
    | '/_app/assistants/$assistantId'
    | '/_app/runs/$runId'
    | '/_app/threads/$threadId'
    | '/_app/traces/$traceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/traces': {
      id: '/_app/traces'
      path: '/traces'
      fullPath: '/traces'
      preLoaderRoute: typeof AppTracesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/threads': {
      id: '/_app/threads'
      path: '/threads'
      fullPath: '/threads'
      preLoaderRoute: typeof AppThreadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/runs': {
      id: '/_app/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof AppRunsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/costs': {
      id: '/_app/costs'
      path: '/costs'
      fullPath: '/costs'
      preLoaderRoute: typeof AppCostsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assistants': {
      id: '/_app/assistants'
      path: '/assistants'
      fullPath: '/assistants'
      preLoaderRoute: typeof AppAssistantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/traces/$traceId': {
      id: '/_app/traces/$traceId'
      path: '/$traceId'
      fullPath: '/traces/$traceId'
      preLoaderRoute: typeof AppTracesTraceIdRouteImport
      parentRoute: typeof AppTracesRoute
    }
    '/_app/threads/$threadId': {
      id: '/_app/threads/$threadId'
      path: '/$threadId'
      fullPath: '/threads/$threadId'
      preLoaderRoute: typeof AppThreadsThreadIdRouteImport
      parentRoute: typeof AppThreadsRoute
    }
    '/_app/runs/$runId': {
      id: '/_app/runs/$runId'
      path: '/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof AppRunsRunIdRouteImport
      parentRoute: typeof AppRunsRoute
    }
    '/_app/assistants/$assistantId': {
      id: '/_app/assistants/$assistantId'
      path: '/$assistantId'
      fullPath: '/assistants/$assistantId'
      preLoaderRoute: typeof AppAssistantsAssistantIdRouteImport
      parentRoute: typeof AppAssistantsRoute
    }
  }
}

interface AppAssistantsRouteChildren {
  AppAssistantsAssistantIdRoute: typeof AppAssistantsAssistantIdRoute
}

const AppAssistantsRouteChildren: AppAssistantsRouteChildren = {
  AppAssistantsAssistantIdRoute: AppAssistantsAssistantIdRoute,
}

const AppAssistantsRouteWithChildren = AppAssistantsRoute._addFileChildren(
  AppAssistantsRouteChildren,
)

interface AppRunsRouteChildren {
  AppRunsRunIdRoute: typeof AppRunsRunIdRoute
}

const AppRunsRouteChildren: AppRunsRouteChildren = {
  AppRunsRunIdRoute: AppRunsRunIdRoute,
}

const AppRunsRouteWithChildren =
  AppRunsRoute._addFileChildren(AppRunsRouteChildren)

interface AppThreadsRouteChildren {
  AppThreadsThreadIdRoute: typeof AppThreadsThreadIdRoute
}

const AppThreadsRouteChildren: AppThreadsRouteChildren = {
  AppThreadsThreadIdRoute: AppThreadsThreadIdRoute,
}

const AppThreadsRouteWithChildren = AppThreadsRoute._addFileChildren(
  AppThreadsRouteChildren,
)

interface AppTracesRouteChildren {
  AppTracesTraceIdRoute: typeof AppTracesTraceIdRoute
}

const AppTracesRouteChildren: AppTracesRouteChildren = {
  AppTracesTraceIdRoute: AppTracesTraceIdRoute,
}

const AppTracesRouteWithChildren = AppTracesRoute._addFileChildren(
  AppTracesRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAssistantsRoute: typeof AppAssistantsRouteWithChildren
  AppCostsRoute: typeof AppCostsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRunsRoute: typeof AppRunsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppThreadsRoute: typeof AppThreadsRouteWithChildren
  AppTracesRoute: typeof AppTracesRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAssistantsRoute: AppAssistantsRouteWithChildren,
  AppCostsRoute: AppCostsRoute,
  AppProfileRoute: AppProfileRoute,
  AppRunsRoute: AppRunsRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppThreadsRoute: AppThreadsRouteWithChildren,
  AppTracesRoute: AppTracesRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
