name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Start the server with '...'
        2. Call the API endpoint '...'
        3. Observe the error '...'
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: The API should return...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Instead, it returned...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Relevant log output
      placeholder: Paste logs here
      render: shell

  - type: input
    id: version
    attributes:
      label: DuraGraph Version
      description: What version are you running?
      placeholder: v0.1.0 or commit hash
    validations:
      required: true

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Method
      description: How are you running DuraGraph?
      options:
        - Docker Compose
        - Docker (manual)
        - Binary (built from source)
        - Fly.io
        - DigitalOcean
        - Render
        - Railway
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: System information
      placeholder: |
        - OS: Ubuntu 22.04
        - Go Version: 1.23.0
        - PostgreSQL Version: 15.3
        - NATS Version: 2.10.0
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: Screenshots, related issues, etc.
