// Package endpoints provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package endpoints

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AssistantCreateIfExists.
const (
	AssistantCreateIfExistsDoNothing AssistantCreateIfExists = "do_nothing"
	AssistantCreateIfExistsRaise     AssistantCreateIfExists = "raise"
)

// Valid indicates whether the value is a known member of the AssistantCreateIfExists enum.
func (e AssistantCreateIfExists) Valid() bool {
	switch e {
	case AssistantCreateIfExistsDoNothing:
		return true
	case AssistantCreateIfExistsRaise:
		return true
	default:
		return false
	}
}

// Defines values for AssistantSearchRequestSelect.
const (
	AssistantSearchRequestSelectAssistantId AssistantSearchRequestSelect = "assistant_id"
	AssistantSearchRequestSelectConfig      AssistantSearchRequestSelect = "config"
	AssistantSearchRequestSelectContext     AssistantSearchRequestSelect = "context"
	AssistantSearchRequestSelectCreatedAt   AssistantSearchRequestSelect = "created_at"
	AssistantSearchRequestSelectDescription AssistantSearchRequestSelect = "description"
	AssistantSearchRequestSelectGraphId     AssistantSearchRequestSelect = "graph_id"
	AssistantSearchRequestSelectMetadata    AssistantSearchRequestSelect = "metadata"
	AssistantSearchRequestSelectName        AssistantSearchRequestSelect = "name"
	AssistantSearchRequestSelectUpdatedAt   AssistantSearchRequestSelect = "updated_at"
	AssistantSearchRequestSelectVersion     AssistantSearchRequestSelect = "version"
)

// Valid indicates whether the value is a known member of the AssistantSearchRequestSelect enum.
func (e AssistantSearchRequestSelect) Valid() bool {
	switch e {
	case AssistantSearchRequestSelectAssistantId:
		return true
	case AssistantSearchRequestSelectConfig:
		return true
	case AssistantSearchRequestSelectContext:
		return true
	case AssistantSearchRequestSelectCreatedAt:
		return true
	case AssistantSearchRequestSelectDescription:
		return true
	case AssistantSearchRequestSelectGraphId:
		return true
	case AssistantSearchRequestSelectMetadata:
		return true
	case AssistantSearchRequestSelectName:
		return true
	case AssistantSearchRequestSelectUpdatedAt:
		return true
	case AssistantSearchRequestSelectVersion:
		return true
	default:
		return false
	}
}

// Defines values for AssistantSearchRequestSortBy.
const (
	AssistantSearchRequestSortByAssistantId AssistantSearchRequestSortBy = "assistant_id"
	AssistantSearchRequestSortByCreatedAt   AssistantSearchRequestSortBy = "created_at"
	AssistantSearchRequestSortByGraphId     AssistantSearchRequestSortBy = "graph_id"
	AssistantSearchRequestSortByName        AssistantSearchRequestSortBy = "name"
	AssistantSearchRequestSortByUpdatedAt   AssistantSearchRequestSortBy = "updated_at"
)

// Valid indicates whether the value is a known member of the AssistantSearchRequestSortBy enum.
func (e AssistantSearchRequestSortBy) Valid() bool {
	switch e {
	case AssistantSearchRequestSortByAssistantId:
		return true
	case AssistantSearchRequestSortByCreatedAt:
		return true
	case AssistantSearchRequestSortByGraphId:
		return true
	case AssistantSearchRequestSortByName:
		return true
	case AssistantSearchRequestSortByUpdatedAt:
		return true
	default:
		return false
	}
}

// Defines values for AssistantSearchRequestSortOrder.
const (
	AssistantSearchRequestSortOrderAsc  AssistantSearchRequestSortOrder = "asc"
	AssistantSearchRequestSortOrderDesc AssistantSearchRequestSortOrder = "desc"
)

// Valid indicates whether the value is a known member of the AssistantSearchRequestSortOrder enum.
func (e AssistantSearchRequestSortOrder) Valid() bool {
	switch e {
	case AssistantSearchRequestSortOrderAsc:
		return true
	case AssistantSearchRequestSortOrderDesc:
		return true
	default:
		return false
	}
}

// Defines values for CronCreateMultitaskStrategy.
const (
	CronCreateMultitaskStrategyEnqueue   CronCreateMultitaskStrategy = "enqueue"
	CronCreateMultitaskStrategyInterrupt CronCreateMultitaskStrategy = "interrupt"
	CronCreateMultitaskStrategyReject    CronCreateMultitaskStrategy = "reject"
	CronCreateMultitaskStrategyRollback  CronCreateMultitaskStrategy = "rollback"
)

// Valid indicates whether the value is a known member of the CronCreateMultitaskStrategy enum.
func (e CronCreateMultitaskStrategy) Valid() bool {
	switch e {
	case CronCreateMultitaskStrategyEnqueue:
		return true
	case CronCreateMultitaskStrategyInterrupt:
		return true
	case CronCreateMultitaskStrategyReject:
		return true
	case CronCreateMultitaskStrategyRollback:
		return true
	default:
		return false
	}
}

// Defines values for CronSearchSelect.
const (
	CronSearchSelectAssistantId CronSearchSelect = "assistant_id"
	CronSearchSelectCreatedAt   CronSearchSelect = "created_at"
	CronSearchSelectCronId      CronSearchSelect = "cron_id"
	CronSearchSelectEndTime     CronSearchSelect = "end_time"
	CronSearchSelectMetadata    CronSearchSelect = "metadata"
	CronSearchSelectNextRunDate CronSearchSelect = "next_run_date"
	CronSearchSelectNow         CronSearchSelect = "now"
	CronSearchSelectPayload     CronSearchSelect = "payload"
	CronSearchSelectSchedule    CronSearchSelect = "schedule"
	CronSearchSelectThreadId    CronSearchSelect = "thread_id"
	CronSearchSelectUpdatedAt   CronSearchSelect = "updated_at"
	CronSearchSelectUserId      CronSearchSelect = "user_id"
)

// Valid indicates whether the value is a known member of the CronSearchSelect enum.
func (e CronSearchSelect) Valid() bool {
	switch e {
	case CronSearchSelectAssistantId:
		return true
	case CronSearchSelectCreatedAt:
		return true
	case CronSearchSelectCronId:
		return true
	case CronSearchSelectEndTime:
		return true
	case CronSearchSelectMetadata:
		return true
	case CronSearchSelectNextRunDate:
		return true
	case CronSearchSelectNow:
		return true
	case CronSearchSelectPayload:
		return true
	case CronSearchSelectSchedule:
		return true
	case CronSearchSelectThreadId:
		return true
	case CronSearchSelectUpdatedAt:
		return true
	case CronSearchSelectUserId:
		return true
	default:
		return false
	}
}

// Defines values for CronSearchSortBy.
const (
	CronSearchSortByAssistantId CronSearchSortBy = "assistant_id"
	CronSearchSortByCreatedAt   CronSearchSortBy = "created_at"
	CronSearchSortByCronId      CronSearchSortBy = "cron_id"
	CronSearchSortByEndTime     CronSearchSortBy = "end_time"
	CronSearchSortByNextRunDate CronSearchSortBy = "next_run_date"
	CronSearchSortByThreadId    CronSearchSortBy = "thread_id"
	CronSearchSortByUpdatedAt   CronSearchSortBy = "updated_at"
)

// Valid indicates whether the value is a known member of the CronSearchSortBy enum.
func (e CronSearchSortBy) Valid() bool {
	switch e {
	case CronSearchSortByAssistantId:
		return true
	case CronSearchSortByCreatedAt:
		return true
	case CronSearchSortByCronId:
		return true
	case CronSearchSortByEndTime:
		return true
	case CronSearchSortByNextRunDate:
		return true
	case CronSearchSortByThreadId:
		return true
	case CronSearchSortByUpdatedAt:
		return true
	default:
		return false
	}
}

// Defines values for CronSearchSortOrder.
const (
	CronSearchSortOrderAsc  CronSearchSortOrder = "asc"
	CronSearchSortOrderDesc CronSearchSortOrder = "desc"
)

// Valid indicates whether the value is a known member of the CronSearchSortOrder enum.
func (e CronSearchSortOrder) Valid() bool {
	switch e {
	case CronSearchSortOrderAsc:
		return true
	case CronSearchSortOrderDesc:
		return true
	default:
		return false
	}
}

// Defines values for RunMultitaskStrategy.
const (
	RunMultitaskStrategyEnqueue   RunMultitaskStrategy = "enqueue"
	RunMultitaskStrategyInterrupt RunMultitaskStrategy = "interrupt"
	RunMultitaskStrategyReject    RunMultitaskStrategy = "reject"
	RunMultitaskStrategyRollback  RunMultitaskStrategy = "rollback"
)

// Valid indicates whether the value is a known member of the RunMultitaskStrategy enum.
func (e RunMultitaskStrategy) Valid() bool {
	switch e {
	case RunMultitaskStrategyEnqueue:
		return true
	case RunMultitaskStrategyInterrupt:
		return true
	case RunMultitaskStrategyReject:
		return true
	case RunMultitaskStrategyRollback:
		return true
	default:
		return false
	}
}

// Defines values for RunStatus.
const (
	RunStatusError       RunStatus = "error"
	RunStatusInterrupted RunStatus = "interrupted"
	RunStatusPending     RunStatus = "pending"
	RunStatusRunning     RunStatus = "running"
	RunStatusSuccess     RunStatus = "success"
	RunStatusTimeout     RunStatus = "timeout"
)

// Valid indicates whether the value is a known member of the RunStatus enum.
func (e RunStatus) Valid() bool {
	switch e {
	case RunStatusError:
		return true
	case RunStatusInterrupted:
		return true
	case RunStatusPending:
		return true
	case RunStatusRunning:
		return true
	case RunStatusSuccess:
		return true
	case RunStatusTimeout:
		return true
	default:
		return false
	}
}

// Defines values for RunCreateStatefulDurability.
const (
	RunCreateStatefulDurabilityAsync RunCreateStatefulDurability = "async"
	RunCreateStatefulDurabilityExit  RunCreateStatefulDurability = "exit"
	RunCreateStatefulDurabilitySync  RunCreateStatefulDurability = "sync"
)

// Valid indicates whether the value is a known member of the RunCreateStatefulDurability enum.
func (e RunCreateStatefulDurability) Valid() bool {
	switch e {
	case RunCreateStatefulDurabilityAsync:
		return true
	case RunCreateStatefulDurabilityExit:
		return true
	case RunCreateStatefulDurabilitySync:
		return true
	default:
		return false
	}
}

// Defines values for RunCreateStatefulIfNotExists.
const (
	RunCreateStatefulIfNotExistsCreate RunCreateStatefulIfNotExists = "create"
	RunCreateStatefulIfNotExistsReject RunCreateStatefulIfNotExists = "reject"
)

// Valid indicates whether the value is a known member of the RunCreateStatefulIfNotExists enum.
func (e RunCreateStatefulIfNotExists) Valid() bool {
	switch e {
	case RunCreateStatefulIfNotExistsCreate:
		return true
	case RunCreateStatefulIfNotExistsReject:
		return true
	default:
		return false
	}
}

// Defines values for RunCreateStatefulMultitaskStrategy.
const (
	RunCreateStatefulMultitaskStrategyEnqueue   RunCreateStatefulMultitaskStrategy = "enqueue"
	RunCreateStatefulMultitaskStrategyInterrupt RunCreateStatefulMultitaskStrategy = "interrupt"
	RunCreateStatefulMultitaskStrategyReject    RunCreateStatefulMultitaskStrategy = "reject"
	RunCreateStatefulMultitaskStrategyRollback  RunCreateStatefulMultitaskStrategy = "rollback"
)

// Valid indicates whether the value is a known member of the RunCreateStatefulMultitaskStrategy enum.
func (e RunCreateStatefulMultitaskStrategy) Valid() bool {
	switch e {
	case RunCreateStatefulMultitaskStrategyEnqueue:
		return true
	case RunCreateStatefulMultitaskStrategyInterrupt:
		return true
	case RunCreateStatefulMultitaskStrategyReject:
		return true
	case RunCreateStatefulMultitaskStrategyRollback:
		return true
	default:
		return false
	}
}

// Defines values for RunCreateStatefulOnDisconnect.
const (
	RunCreateStatefulOnDisconnectCancel   RunCreateStatefulOnDisconnect = "cancel"
	RunCreateStatefulOnDisconnectContinue RunCreateStatefulOnDisconnect = "continue"
)

// Valid indicates whether the value is a known member of the RunCreateStatefulOnDisconnect enum.
func (e RunCreateStatefulOnDisconnect) Valid() bool {
	switch e {
	case RunCreateStatefulOnDisconnectCancel:
		return true
	case RunCreateStatefulOnDisconnectContinue:
		return true
	default:
		return false
	}
}

// Defines values for RunCreateStatelessDurability.
const (
	RunCreateStatelessDurabilityAsync RunCreateStatelessDurability = "async"
	RunCreateStatelessDurabilityExit  RunCreateStatelessDurability = "exit"
	RunCreateStatelessDurabilitySync  RunCreateStatelessDurability = "sync"
)

// Valid indicates whether the value is a known member of the RunCreateStatelessDurability enum.
func (e RunCreateStatelessDurability) Valid() bool {
	switch e {
	case RunCreateStatelessDurabilityAsync:
		return true
	case RunCreateStatelessDurabilityExit:
		return true
	case RunCreateStatelessDurabilitySync:
		return true
	default:
		return false
	}
}

// Defines values for RunCreateStatelessOnCompletion.
const (
	RunCreateStatelessOnCompletionDelete RunCreateStatelessOnCompletion = "delete"
	RunCreateStatelessOnCompletionKeep   RunCreateStatelessOnCompletion = "keep"
)

// Valid indicates whether the value is a known member of the RunCreateStatelessOnCompletion enum.
func (e RunCreateStatelessOnCompletion) Valid() bool {
	switch e {
	case RunCreateStatelessOnCompletionDelete:
		return true
	case RunCreateStatelessOnCompletionKeep:
		return true
	default:
		return false
	}
}

// Defines values for RunCreateStatelessOnDisconnect.
const (
	RunCreateStatelessOnDisconnectCancel   RunCreateStatelessOnDisconnect = "cancel"
	RunCreateStatelessOnDisconnectContinue RunCreateStatelessOnDisconnect = "continue"
)

// Valid indicates whether the value is a known member of the RunCreateStatelessOnDisconnect enum.
func (e RunCreateStatelessOnDisconnect) Valid() bool {
	switch e {
	case RunCreateStatelessOnDisconnectCancel:
		return true
	case RunCreateStatelessOnDisconnectContinue:
		return true
	default:
		return false
	}
}

// Defines values for RunsCancelStatus.
const (
	RunsCancelStatusAll     RunsCancelStatus = "all"
	RunsCancelStatusPending RunsCancelStatus = "pending"
	RunsCancelStatusRunning RunsCancelStatus = "running"
)

// Valid indicates whether the value is a known member of the RunsCancelStatus enum.
func (e RunsCancelStatus) Valid() bool {
	switch e {
	case RunsCancelStatusAll:
		return true
	case RunsCancelStatusPending:
		return true
	case RunsCancelStatusRunning:
		return true
	default:
		return false
	}
}

// Defines values for ThreadStatus.
const (
	ThreadStatusBusy        ThreadStatus = "busy"
	ThreadStatusError       ThreadStatus = "error"
	ThreadStatusIdle        ThreadStatus = "idle"
	ThreadStatusInterrupted ThreadStatus = "interrupted"
)

// Valid indicates whether the value is a known member of the ThreadStatus enum.
func (e ThreadStatus) Valid() bool {
	switch e {
	case ThreadStatusBusy:
		return true
	case ThreadStatusError:
		return true
	case ThreadStatusIdle:
		return true
	case ThreadStatusInterrupted:
		return true
	default:
		return false
	}
}

// Defines values for ThreadCountRequestStatus.
const (
	ThreadCountRequestStatusBusy        ThreadCountRequestStatus = "busy"
	ThreadCountRequestStatusError       ThreadCountRequestStatus = "error"
	ThreadCountRequestStatusIdle        ThreadCountRequestStatus = "idle"
	ThreadCountRequestStatusInterrupted ThreadCountRequestStatus = "interrupted"
)

// Valid indicates whether the value is a known member of the ThreadCountRequestStatus enum.
func (e ThreadCountRequestStatus) Valid() bool {
	switch e {
	case ThreadCountRequestStatusBusy:
		return true
	case ThreadCountRequestStatusError:
		return true
	case ThreadCountRequestStatusIdle:
		return true
	case ThreadCountRequestStatusInterrupted:
		return true
	default:
		return false
	}
}

// Defines values for ThreadCreateIfExists.
const (
	ThreadCreateIfExistsDoNothing ThreadCreateIfExists = "do_nothing"
	ThreadCreateIfExistsRaise     ThreadCreateIfExists = "raise"
)

// Valid indicates whether the value is a known member of the ThreadCreateIfExists enum.
func (e ThreadCreateIfExists) Valid() bool {
	switch e {
	case ThreadCreateIfExistsDoNothing:
		return true
	case ThreadCreateIfExistsRaise:
		return true
	default:
		return false
	}
}

// Defines values for ThreadCreateTtlStrategy.
const (
	ThreadCreateTtlStrategyDelete ThreadCreateTtlStrategy = "delete"
)

// Valid indicates whether the value is a known member of the ThreadCreateTtlStrategy enum.
func (e ThreadCreateTtlStrategy) Valid() bool {
	switch e {
	case ThreadCreateTtlStrategyDelete:
		return true
	default:
		return false
	}
}

// Defines values for ThreadPatchTtlStrategy.
const (
	Delete ThreadPatchTtlStrategy = "delete"
)

// Valid indicates whether the value is a known member of the ThreadPatchTtlStrategy enum.
func (e ThreadPatchTtlStrategy) Valid() bool {
	switch e {
	case Delete:
		return true
	default:
		return false
	}
}

// Defines values for ThreadSearchRequestSelect.
const (
	ThreadSearchRequestSelectConfig     ThreadSearchRequestSelect = "config"
	ThreadSearchRequestSelectContext    ThreadSearchRequestSelect = "context"
	ThreadSearchRequestSelectCreatedAt  ThreadSearchRequestSelect = "created_at"
	ThreadSearchRequestSelectInterrupts ThreadSearchRequestSelect = "interrupts"
	ThreadSearchRequestSelectMetadata   ThreadSearchRequestSelect = "metadata"
	ThreadSearchRequestSelectStatus     ThreadSearchRequestSelect = "status"
	ThreadSearchRequestSelectThreadId   ThreadSearchRequestSelect = "thread_id"
	ThreadSearchRequestSelectUpdatedAt  ThreadSearchRequestSelect = "updated_at"
	ThreadSearchRequestSelectValues     ThreadSearchRequestSelect = "values"
)

// Valid indicates whether the value is a known member of the ThreadSearchRequestSelect enum.
func (e ThreadSearchRequestSelect) Valid() bool {
	switch e {
	case ThreadSearchRequestSelectConfig:
		return true
	case ThreadSearchRequestSelectContext:
		return true
	case ThreadSearchRequestSelectCreatedAt:
		return true
	case ThreadSearchRequestSelectInterrupts:
		return true
	case ThreadSearchRequestSelectMetadata:
		return true
	case ThreadSearchRequestSelectStatus:
		return true
	case ThreadSearchRequestSelectThreadId:
		return true
	case ThreadSearchRequestSelectUpdatedAt:
		return true
	case ThreadSearchRequestSelectValues:
		return true
	default:
		return false
	}
}

// Defines values for ThreadSearchRequestSortBy.
const (
	ThreadSearchRequestSortByCreatedAt ThreadSearchRequestSortBy = "created_at"
	ThreadSearchRequestSortByStatus    ThreadSearchRequestSortBy = "status"
	ThreadSearchRequestSortByThreadId  ThreadSearchRequestSortBy = "thread_id"
	ThreadSearchRequestSortByUpdatedAt ThreadSearchRequestSortBy = "updated_at"
)

// Valid indicates whether the value is a known member of the ThreadSearchRequestSortBy enum.
func (e ThreadSearchRequestSortBy) Valid() bool {
	switch e {
	case ThreadSearchRequestSortByCreatedAt:
		return true
	case ThreadSearchRequestSortByStatus:
		return true
	case ThreadSearchRequestSortByThreadId:
		return true
	case ThreadSearchRequestSortByUpdatedAt:
		return true
	default:
		return false
	}
}

// Defines values for ThreadSearchRequestSortOrder.
const (
	Asc  ThreadSearchRequestSortOrder = "asc"
	Desc ThreadSearchRequestSortOrder = "desc"
)

// Valid indicates whether the value is a known member of the ThreadSearchRequestSortOrder enum.
func (e ThreadSearchRequestSortOrder) Valid() bool {
	switch e {
	case Asc:
		return true
	case Desc:
		return true
	default:
		return false
	}
}

// Defines values for ThreadSearchRequestStatus.
const (
	ThreadSearchRequestStatusBusy        ThreadSearchRequestStatus = "busy"
	ThreadSearchRequestStatusError       ThreadSearchRequestStatus = "error"
	ThreadSearchRequestStatusIdle        ThreadSearchRequestStatus = "idle"
	ThreadSearchRequestStatusInterrupted ThreadSearchRequestStatus = "interrupted"
)

// Valid indicates whether the value is a known member of the ThreadSearchRequestStatus enum.
func (e ThreadSearchRequestStatus) Valid() bool {
	switch e {
	case ThreadSearchRequestStatusBusy:
		return true
	case ThreadSearchRequestStatusError:
		return true
	case ThreadSearchRequestStatusIdle:
		return true
	case ThreadSearchRequestStatusInterrupted:
		return true
	default:
		return false
	}
}

// Defines values for PostA2aParamsAccept.
const (
	Applicationjson PostA2aParamsAccept = "application/json"
)

// Valid indicates whether the value is a known member of the PostA2aParamsAccept enum.
func (e PostA2aParamsAccept) Valid() bool {
	switch e {
	case Applicationjson:
		return true
	default:
		return false
	}
}

// Defines values for PostA2aJSONBodyJsonrpc.
const (
	PostA2aJSONBodyJsonrpcN20 PostA2aJSONBodyJsonrpc = "2.0"
)

// Valid indicates whether the value is a known member of the PostA2aJSONBodyJsonrpc enum.
func (e PostA2aJSONBodyJsonrpc) Valid() bool {
	switch e {
	case PostA2aJSONBodyJsonrpcN20:
		return true
	default:
		return false
	}
}

// Defines values for PostA2aJSONBodyMethod.
const (
	Messagesend PostA2aJSONBodyMethod = "message/send"
	Tasksget    PostA2aJSONBodyMethod = "tasks/get"
)

// Valid indicates whether the value is a known member of the PostA2aJSONBodyMethod enum.
func (e PostA2aJSONBodyMethod) Valid() bool {
	switch e {
	case Messagesend:
		return true
	case Tasksget:
		return true
	default:
		return false
	}
}

// Defines values for PostA2a200JSONResponseBodyJsonrpc.
const (
	PostA2a200JSONResponseBodyJsonrpcN20 PostA2a200JSONResponseBodyJsonrpc = "2.0"
)

// Valid indicates whether the value is a known member of the PostA2a200JSONResponseBodyJsonrpc enum.
func (e PostA2a200JSONResponseBodyJsonrpc) Valid() bool {
	switch e {
	case PostA2a200JSONResponseBodyJsonrpcN20:
		return true
	default:
		return false
	}
}

// Defines values for PostMcpParamsAccept.
const (
	ApplicationjsonTexteventStream PostMcpParamsAccept = "application/json, text/event-stream"
)

// Valid indicates whether the value is a known member of the PostMcpParamsAccept enum.
func (e PostMcpParamsAccept) Valid() bool {
	switch e {
	case ApplicationjsonTexteventStream:
		return true
	default:
		return false
	}
}

// Defines values for SystemMetricsMetricsGetParamsFormat.
const (
	Json       SystemMetricsMetricsGetParamsFormat = "json"
	Prometheus SystemMetricsMetricsGetParamsFormat = "prometheus"
)

// Valid indicates whether the value is a known member of the SystemMetricsMetricsGetParamsFormat enum.
func (e SystemMetricsMetricsGetParamsFormat) Valid() bool {
	switch e {
	case Json:
		return true
	case Prometheus:
		return true
	default:
		return false
	}
}

// Defines values for HealthCheckOkGetParamsCheckDb.
const (
	N0 HealthCheckOkGetParamsCheckDb = 0
	N1 HealthCheckOkGetParamsCheckDb = 1
)

// Valid indicates whether the value is a known member of the HealthCheckOkGetParamsCheckDb enum.
func (e HealthCheckOkGetParamsCheckDb) Valid() bool {
	switch e {
	case N0:
		return true
	case N1:
		return true
	default:
		return false
	}
}

// Defines values for HealthCheckOkGet200JSONResponseBodyOk.
const (
	True HealthCheckOkGet200JSONResponseBodyOk = true
)

// Valid indicates whether the value is a known member of the HealthCheckOkGet200JSONResponseBodyOk enum.
func (e HealthCheckOkGet200JSONResponseBodyOk) Valid() bool {
	switch e {
	case True:
		return true
	default:
		return false
	}
}

// Defines values for CancelRunsPostParamsAction.
const (
	CancelRunsPostParamsActionInterrupt CancelRunsPostParamsAction = "interrupt"
	CancelRunsPostParamsActionRollback  CancelRunsPostParamsAction = "rollback"
)

// Valid indicates whether the value is a known member of the CancelRunsPostParamsAction enum.
func (e CancelRunsPostParamsAction) Valid() bool {
	switch e {
	case CancelRunsPostParamsActionInterrupt:
		return true
	case CancelRunsPostParamsActionRollback:
		return true
	default:
		return false
	}
}

// Defines values for ListRunsHttpThreadsThreadIdRunsGetParamsStatus.
const (
	ListRunsHttpThreadsThreadIdRunsGetParamsStatusError       ListRunsHttpThreadsThreadIdRunsGetParamsStatus = "error"
	ListRunsHttpThreadsThreadIdRunsGetParamsStatusInterrupted ListRunsHttpThreadsThreadIdRunsGetParamsStatus = "interrupted"
	ListRunsHttpThreadsThreadIdRunsGetParamsStatusPending     ListRunsHttpThreadsThreadIdRunsGetParamsStatus = "pending"
	ListRunsHttpThreadsThreadIdRunsGetParamsStatusSuccess     ListRunsHttpThreadsThreadIdRunsGetParamsStatus = "success"
	ListRunsHttpThreadsThreadIdRunsGetParamsStatusTimeout     ListRunsHttpThreadsThreadIdRunsGetParamsStatus = "timeout"
)

// Valid indicates whether the value is a known member of the ListRunsHttpThreadsThreadIdRunsGetParamsStatus enum.
func (e ListRunsHttpThreadsThreadIdRunsGetParamsStatus) Valid() bool {
	switch e {
	case ListRunsHttpThreadsThreadIdRunsGetParamsStatusError:
		return true
	case ListRunsHttpThreadsThreadIdRunsGetParamsStatusInterrupted:
		return true
	case ListRunsHttpThreadsThreadIdRunsGetParamsStatusPending:
		return true
	case ListRunsHttpThreadsThreadIdRunsGetParamsStatusSuccess:
		return true
	case ListRunsHttpThreadsThreadIdRunsGetParamsStatusTimeout:
		return true
	default:
		return false
	}
}

// Defines values for ListRunsHttpThreadsThreadIdRunsGetParamsSelect.
const (
	AssistantId       ListRunsHttpThreadsThreadIdRunsGetParamsSelect = "assistant_id"
	CreatedAt         ListRunsHttpThreadsThreadIdRunsGetParamsSelect = "created_at"
	Kwargs            ListRunsHttpThreadsThreadIdRunsGetParamsSelect = "kwargs"
	Metadata          ListRunsHttpThreadsThreadIdRunsGetParamsSelect = "metadata"
	MultitaskStrategy ListRunsHttpThreadsThreadIdRunsGetParamsSelect = "multitask_strategy"
	RunId             ListRunsHttpThreadsThreadIdRunsGetParamsSelect = "run_id"
	Status            ListRunsHttpThreadsThreadIdRunsGetParamsSelect = "status"
	ThreadId          ListRunsHttpThreadsThreadIdRunsGetParamsSelect = "thread_id"
	UpdatedAt         ListRunsHttpThreadsThreadIdRunsGetParamsSelect = "updated_at"
)

// Valid indicates whether the value is a known member of the ListRunsHttpThreadsThreadIdRunsGetParamsSelect enum.
func (e ListRunsHttpThreadsThreadIdRunsGetParamsSelect) Valid() bool {
	switch e {
	case AssistantId:
		return true
	case CreatedAt:
		return true
	case Kwargs:
		return true
	case Metadata:
		return true
	case MultitaskStrategy:
		return true
	case RunId:
		return true
	case Status:
		return true
	case ThreadId:
		return true
	case UpdatedAt:
		return true
	default:
		return false
	}
}

// Defines values for CancelRunHttpThreadsThreadIdRunsRunIdCancelPostParamsAction.
const (
	CancelRunHttpThreadsThreadIdRunsRunIdCancelPostParamsActionInterrupt CancelRunHttpThreadsThreadIdRunsRunIdCancelPostParamsAction = "interrupt"
	CancelRunHttpThreadsThreadIdRunsRunIdCancelPostParamsActionRollback  CancelRunHttpThreadsThreadIdRunsRunIdCancelPostParamsAction = "rollback"
)

// Valid indicates whether the value is a known member of the CancelRunHttpThreadsThreadIdRunsRunIdCancelPostParamsAction enum.
func (e CancelRunHttpThreadsThreadIdRunsRunIdCancelPostParamsAction) Valid() bool {
	switch e {
	case CancelRunHttpThreadsThreadIdRunsRunIdCancelPostParamsActionInterrupt:
		return true
	case CancelRunHttpThreadsThreadIdRunsRunIdCancelPostParamsActionRollback:
		return true
	default:
		return false
	}
}

// Assistant defines model for Assistant.
type Assistant struct {
	// AssistantId The ID of the assistant.
	AssistantId openapi_types.UUID `json:"assistant_id"`

	// Config The assistant config.
	Config struct {
		Configurable   *map[string]interface{} `json:"configurable,omitempty"`
		RecursionLimit *int                    `json:"recursion_limit,omitempty"`
		Tags           *[]string               `json:"tags,omitempty"`
	} `json:"config"`

	// Context Static context added to the assistant.
	Context *map[string]interface{} `json:"context,omitempty"`

	// CreatedAt The time the assistant was created.
	CreatedAt time.Time `json:"created_at"`

	// Description The description of the assistant
	Description *string `json:"description,omitempty"`

	// GraphId The ID of the graph.
	GraphId string `json:"graph_id"`

	// Metadata The assistant metadata.
	Metadata map[string]interface{} `json:"metadata"`

	// Name The name of the assistant
	Name *string `json:"name,omitempty"`

	// UpdatedAt The last time the assistant was updated.
	UpdatedAt time.Time `json:"updated_at"`

	// Version The version of the assistant
	Version *int `json:"version,omitempty"`
}

// AssistantCountRequest Payload for counting assistants.
type AssistantCountRequest struct {
	// GraphId The ID of the graph to filter by. The graph ID is normally set in your langgraph.json configuration.
	GraphId *string `json:"graph_id,omitempty"`

	// Metadata Metadata to filter by. Exact match filter for each KV pair.
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
}

// AssistantCreate Payload for creating an assistant.
type AssistantCreate struct {
	// AssistantId The ID of the assistant. If not provided, a random UUID will be generated.
	AssistantId *openapi_types.UUID `json:"assistant_id,omitempty"`

	// Config Configuration to use for the graph. Useful when graph is configurable and you want to create different assistants based on different configurations.
	Config *map[string]interface{} `json:"config,omitempty"`

	// Context Static context added to the assistant.
	Context *map[string]interface{} `json:"context,omitempty"`

	// Description The description of the assistant. Defaults to null.
	Description *string `json:"description,omitempty"`

	// GraphId The ID of the graph the assistant should use. The graph ID is normally set in your langgraph.json configuration.
	GraphId string `json:"graph_id"`

	// IfExists How to handle duplicate creation. Must be either 'raise' (raise error if duplicate), or 'do_nothing' (return existing assistant).
	IfExists *AssistantCreateIfExists `json:"if_exists,omitempty"`

	// Metadata Metadata to add to assistant.
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// Name The name of the assistant. Defaults to 'Untitled'.
	Name *string `json:"name,omitempty"`
}

// AssistantCreateIfExists How to handle duplicate creation. Must be either 'raise' (raise error if duplicate), or 'do_nothing' (return existing assistant).
type AssistantCreateIfExists string

// AssistantPatch Payload for updating an assistant.
type AssistantPatch struct {
	// Config Configuration to use for the graph. Useful when graph is configurable and you want to update the assistant's configuration.
	Config *map[string]interface{} `json:"config,omitempty"`

	// Context Static context added to the assistant.
	Context *map[string]interface{} `json:"context,omitempty"`

	// Description The new description for the assistant. If not provided, assistant will keep its current description.
	Description *string `json:"description,omitempty"`

	// GraphId The ID of the graph the assistant should use. The graph ID is normally set in your langgraph.json configuration. If not provided, assistant will keep pointing to same graph.
	GraphId *string `json:"graph_id,omitempty"`

	// Metadata Metadata to merge with existing assistant metadata.
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// Name The new name for the assistant. If not provided, assistant will keep its current name.
	Name *string `json:"name,omitempty"`
}

// AssistantSearchRequest Payload for listing assistants.
type AssistantSearchRequest struct {
	// GraphId The ID of the graph to filter by. The graph ID is normally set in your langgraph.json configuration.
	GraphId *string `json:"graph_id,omitempty"`

	// Limit The maximum number of results to return.
	Limit *int `json:"limit,omitempty"`

	// Metadata Metadata to filter by. Exact match filter for each KV pair.
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// Offset The number of results to skip.
	Offset *int `json:"offset,omitempty"`

	// Select Specify which fields to return. If not provided, all fields are returned.
	Select *[]AssistantSearchRequestSelect `json:"select,omitempty"`

	// SortBy The field to sort by.
	SortBy *AssistantSearchRequestSortBy `json:"sort_by,omitempty"`

	// SortOrder The order to sort by.
	SortOrder *AssistantSearchRequestSortOrder `json:"sort_order,omitempty"`
}

// AssistantSearchRequestSelect defines model for AssistantSearchRequest.Select.
type AssistantSearchRequestSelect string

// AssistantSearchRequestSortBy The field to sort by.
type AssistantSearchRequestSortBy string

// AssistantSearchRequestSortOrder The order to sort by.
type AssistantSearchRequestSortOrder string

// AssistantVersionChange Payload for changing the version of an assistant.
type AssistantVersionChange struct {
	// Version The assistant version.
	Version *int `json:"version,omitempty"`
}

// AssistantVersionsSearchRequest Payload for listing assistant versions.
type AssistantVersionsSearchRequest struct {
	// Limit The maximum number of versions to return.
	Limit *int `json:"limit,omitempty"`

	// Metadata Metadata to filter versions by. Exact match filter for each KV pair.
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// Offset The number of versions to skip.
	Offset *int `json:"offset,omitempty"`
}

// CheckpointConfig Checkpoint config.
type CheckpointConfig struct {
	// CheckpointId Optional unique identifier for the checkpoint itself.
	CheckpointId *string `json:"checkpoint_id,omitempty"`

	// CheckpointMap Optional dictionary containing checkpoint-specific data.
	CheckpointMap *map[string]interface{} `json:"checkpoint_map,omitempty"`

	// CheckpointNs Namespace for the checkpoint, used for organization and retrieval.
	CheckpointNs *string `json:"checkpoint_ns,omitempty"`

	// ThreadId Unique identifier for the thread associated with this checkpoint.
	ThreadId *string `json:"thread_id,omitempty"`
}

// Command The command to run.
type Command struct {
	// Goto Name of the node(s) to navigate to next or node(s) to be executed with a provided input.
	Goto interface{} `json:"goto,omitempty"`

	// Resume A value to pass to an interrupted node.
	Resume *map[string]interface{} `json:"resume,omitempty"`

	// Update An update to the state.
	Update *map[string]interface{} `json:"update,omitempty"`
}

// Config defines model for Config.
type Config struct {
	Configurable   *map[string]interface{} `json:"configurable,omitempty"`
	RecursionLimit *int                    `json:"recursion_limit,omitempty"`
	Tags           *[]string               `json:"tags,omitempty"`
}

// Cron Represents a scheduled task.
type Cron struct {
	// AssistantId The ID of the assistant.
	AssistantId *openapi_types.UUID `json:"assistant_id,omitempty"`

	// CreatedAt The time the cron was created.
	CreatedAt time.Time `json:"created_at"`

	// CronId The ID of the cron.
	CronId openapi_types.UUID `json:"cron_id"`

	// EndTime The end date to stop running the cron.
	EndTime time.Time `json:"end_time"`

	// Metadata The cron metadata.
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// NextRunDate The next run date of the cron.
	NextRunDate *time.Time `json:"next_run_date,omitempty"`

	// Payload The run payload to use for creating new run.
	Payload map[string]interface{} `json:"payload"`

	// Schedule The schedule to run, cron format.
	Schedule string `json:"schedule"`

	// ThreadId The ID of the thread.
	ThreadId openapi_types.UUID `json:"thread_id"`

	// UpdatedAt The last time the cron was updated.
	UpdatedAt time.Time `json:"updated_at"`

	// UserId The ID of the user.
	UserId *string `json:"user_id,omitempty"`
}

// CronCountRequest Payload for counting crons
type CronCountRequest struct {
	// AssistantId The assistant ID or graph name to search for.
	AssistantId *openapi_types.UUID `json:"assistant_id,omitempty"`

	// ThreadId The thread ID to search for.
	ThreadId *openapi_types.UUID `json:"thread_id,omitempty"`
}

// CronCreate Payload for creating a cron job.
type CronCreate struct {
	// AssistantId The assistant ID or graph name to run. If using graph name, will default to the assistant automatically created from that graph by the server.
	AssistantId interface{} `json:"assistant_id"`

	// Config The configuration for the assistant.
	Config *struct {
		Configurable   *map[string]interface{} `json:"configurable,omitempty"`
		RecursionLimit *int                    `json:"recursion_limit,omitempty"`
		Tags           *[]string               `json:"tags,omitempty"`
	} `json:"config,omitempty"`

	// Context Static context added to the assistant.
	Context *map[string]interface{} `json:"context,omitempty"`

	// EndTime The end date to stop running the cron.
	EndTime *time.Time `json:"end_time,omitempty"`

	// Input The input to the graph.
	Input interface{} `json:"input,omitempty"`

	// InterruptAfter Nodes to interrupt immediately after they get executed.
	InterruptAfter interface{} `json:"interrupt_after,omitempty"`

	// InterruptBefore Nodes to interrupt immediately before they get executed.
	InterruptBefore interface{} `json:"interrupt_before,omitempty"`

	// Metadata Metadata to assign to the cron job runs.
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// MultitaskStrategy Multitask strategy to use. Must be one of 'reject', 'interrupt', 'rollback', or 'enqueue'.
	MultitaskStrategy *CronCreateMultitaskStrategy `json:"multitask_strategy,omitempty"`

	// Schedule The cron schedule to execute this job on.
	Schedule string `json:"schedule"`

	// Webhook Webhook to call after LangGraph API call is done.
	Webhook *string `json:"webhook,omitempty"`
}

// CronCreateMultitaskStrategy Multitask strategy to use. Must be one of 'reject', 'interrupt', 'rollback', or 'enqueue'.
type CronCreateMultitaskStrategy string

// CronSearch Payload for listing crons
type CronSearch struct {
	// AssistantId The assistant ID or graph name to filter by using exact match.
	AssistantId *openapi_types.UUID `json:"assistant_id,omitempty"`

	// Limit The maximum number of results to return.
	Limit *int `json:"limit,omitempty"`

	// Offset The number of results to skip.
	Offset *int `json:"offset,omitempty"`

	// Select Specify which fields to return. If not provided, all fields are returned.
	Select *[]CronSearchSelect `json:"select,omitempty"`

	// SortBy The field to sort by.
	SortBy *CronSearchSortBy `json:"sort_by,omitempty"`

	// SortOrder The order to sort by.
	SortOrder *CronSearchSortOrder `json:"sort_order,omitempty"`

	// ThreadId The thread ID to search for.
	ThreadId *openapi_types.UUID `json:"thread_id,omitempty"`
}

// CronSearchSelect defines model for CronSearch.Select.
type CronSearchSelect string

// CronSearchSortBy The field to sort by.
type CronSearchSortBy string

// CronSearchSortOrder The order to sort by.
type CronSearchSortOrder string

// ErrorResponse Error message returned from the server
type ErrorResponse = string

// GraphSchema Defines the structure and properties of a graph.
type GraphSchema struct {
	// ConfigSchema The schema for the graph config. Missing if unable to generate JSON schema from graph.
	ConfigSchema *map[string]interface{} `json:"config_schema,omitempty"`

	// ContextSchema The schema for the graph context. Missing if unable to generate JSON schema from graph.
	ContextSchema *map[string]interface{} `json:"context_schema,omitempty"`

	// GraphId The ID of the graph.
	GraphId string `json:"graph_id"`

	// InputSchema The schema for the graph input. Missing if unable to generate JSON schema from graph.
	InputSchema *map[string]interface{} `json:"input_schema,omitempty"`

	// OutputSchema The schema for the graph output. Missing if unable to generate JSON schema from graph.
	OutputSchema *map[string]interface{} `json:"output_schema,omitempty"`

	// StateSchema The schema for the graph state. Missing if unable to generate JSON schema from graph.
	StateSchema map[string]interface{} `json:"state_schema"`
}

// GraphSchemaNoId Defines the structure and properties of a graph without an ID.
type GraphSchemaNoId struct {
	// ConfigSchema The schema for the graph config. Missing if unable to generate JSON schema from graph.
	ConfigSchema *map[string]interface{} `json:"config_schema,omitempty"`

	// ContextSchema The schema for the graph context. Missing if unable to generate JSON schema from graph.
	ContextSchema *map[string]interface{} `json:"context_schema,omitempty"`

	// InputSchema The schema for the graph input. Missing if unable to generate JSON schema from graph.
	InputSchema map[string]interface{} `json:"input_schema"`

	// OutputSchema The schema for the graph output. Missing if unable to generate JSON schema from graph.
	OutputSchema map[string]interface{} `json:"output_schema"`

	// StateSchema The schema for the graph state. Missing if unable to generate JSON schema from graph.
	StateSchema map[string]interface{} `json:"state_schema"`
}

// Interrupt defines model for Interrupt.
type Interrupt struct {
	Id    *string                `json:"id,omitempty"`
	Value map[string]interface{} `json:"value"`
}

// Item Represents a single document or data entry in the graph's Store. Items are used to store cross-thread memories.
type Item struct {
	// CreatedAt The timestamp when the item was created.
	CreatedAt time.Time `json:"created_at"`

	// Key The unique identifier of the item within its namespace. In general, keys needn't be globally unique.
	Key string `json:"key"`

	// Namespace The namespace of the item. A namespace is analogous to a document's directory.
	Namespace []string `json:"namespace"`

	// UpdatedAt The timestamp when the item was last updated.
	UpdatedAt time.Time `json:"updated_at"`

	// Value The value stored in the item. This is the document itself.
	Value map[string]interface{} `json:"value"`
}

// ListNamespaceResponse defines model for ListNamespaceResponse.
type ListNamespaceResponse = [][]string

// Run defines model for Run.
type Run struct {
	// AssistantId The assistant that was used for this run.
	AssistantId openapi_types.UUID `json:"assistant_id"`

	// CreatedAt The time the run was created.
	CreatedAt time.Time              `json:"created_at"`
	Kwargs    map[string]interface{} `json:"kwargs"`

	// Metadata The run metadata.
	Metadata map[string]interface{} `json:"metadata"`

	// MultitaskStrategy Strategy to handle concurrent runs on the same thread.
	MultitaskStrategy RunMultitaskStrategy `json:"multitask_strategy"`

	// RunId The ID of the run.
	RunId openapi_types.UUID `json:"run_id"`

	// Status The status of the run. One of 'pending', 'running', 'error', 'success', 'timeout', 'interrupted'.
	Status RunStatus `json:"status"`

	// ThreadId The ID of the thread.
	ThreadId openapi_types.UUID `json:"thread_id"`

	// UpdatedAt The last time the run was updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// RunMultitaskStrategy Strategy to handle concurrent runs on the same thread.
type RunMultitaskStrategy string

// RunStatus The status of the run. One of 'pending', 'running', 'error', 'success', 'timeout', 'interrupted'.
type RunStatus string

// RunBatchCreate Payload for creating a batch of runs.
type RunBatchCreate = []RunCreateStateless

// RunCreateStateful Payload for creating a run.
type RunCreateStateful struct {
	// AfterSeconds The number of seconds to wait before starting the run. Use to schedule future runs.
	AfterSeconds *float32 `json:"after_seconds,omitempty"`

	// AssistantId The assistant ID or graph name to run. If using graph name, will default to first assistant created from that graph.
	AssistantId interface{} `json:"assistant_id"`

	// Checkpoint Checkpoint config.
	Checkpoint *CheckpointConfig `json:"checkpoint,omitempty"`

	// CheckpointDuring Whether to checkpoint during the run.
	CheckpointDuring *bool `json:"checkpoint_during,omitempty"`

	// Command The input to the graph.
	Command interface{} `json:"command,omitempty"`

	// Config The configuration for the assistant.
	Config *struct {
		Configurable   *map[string]interface{} `json:"configurable,omitempty"`
		RecursionLimit *int                    `json:"recursion_limit,omitempty"`
		Tags           *[]string               `json:"tags,omitempty"`
	} `json:"config,omitempty"`

	// Context Static context added to the assistant.
	Context *map[string]interface{} `json:"context,omitempty"`

	// Durability Durability level for the run. Must be one of 'sync', 'async', or 'exit'.
	Durability *RunCreateStatefulDurability `json:"durability,omitempty"`

	// FeedbackKeys Feedback keys to assign to run.
	FeedbackKeys *[]string `json:"feedback_keys,omitempty"`

	// IfNotExists How to handle missing thread. Must be either 'reject' (raise error if missing), or 'create' (create new thread).
	IfNotExists *RunCreateStatefulIfNotExists `json:"if_not_exists,omitempty"`

	// Input The input to the graph.
	Input interface{} `json:"input,omitempty"`

	// InterruptAfter Nodes to interrupt immediately after they get executed.
	InterruptAfter interface{} `json:"interrupt_after,omitempty"`

	// InterruptBefore Nodes to interrupt immediately before they get executed.
	InterruptBefore interface{} `json:"interrupt_before,omitempty"`

	// Metadata Metadata to assign to the run.
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// MultitaskStrategy Multitask strategy to use. Must be one of 'reject', 'interrupt', 'rollback', or 'enqueue'.
	MultitaskStrategy *RunCreateStatefulMultitaskStrategy `json:"multitask_strategy,omitempty"`

	// OnDisconnect The disconnect mode to use. Must be one of 'cancel' or 'continue'.
	OnDisconnect *RunCreateStatefulOnDisconnect `json:"on_disconnect,omitempty"`

	// StreamMode The stream mode(s) to use.
	StreamMode interface{} `json:"stream_mode,omitempty"`

	// StreamResumable Whether to persist the stream chunks in order to resume the stream later.
	StreamResumable *bool `json:"stream_resumable,omitempty"`

	// StreamSubgraphs Whether to stream output from subgraphs.
	StreamSubgraphs *bool `json:"stream_subgraphs,omitempty"`

	// Webhook Webhook to call after LangGraph API call is done.
	Webhook *string `json:"webhook,omitempty"`
}

// RunCreateStatefulDurability Durability level for the run. Must be one of 'sync', 'async', or 'exit'.
type RunCreateStatefulDurability string

// RunCreateStatefulIfNotExists How to handle missing thread. Must be either 'reject' (raise error if missing), or 'create' (create new thread).
type RunCreateStatefulIfNotExists string

// RunCreateStatefulMultitaskStrategy Multitask strategy to use. Must be one of 'reject', 'interrupt', 'rollback', or 'enqueue'.
type RunCreateStatefulMultitaskStrategy string

// RunCreateStatefulOnDisconnect The disconnect mode to use. Must be one of 'cancel' or 'continue'.
type RunCreateStatefulOnDisconnect string

// RunCreateStateless Payload for creating a run.
type RunCreateStateless struct {
	// AfterSeconds The number of seconds to wait before starting the run. Use to schedule future runs.
	AfterSeconds *float32 `json:"after_seconds,omitempty"`

	// AssistantId The assistant ID or graph name to run. If using graph name, will default to first assistant created from that graph.
	AssistantId interface{} `json:"assistant_id"`

	// CheckpointDuring Whether to checkpoint during the run.
	CheckpointDuring *bool `json:"checkpoint_during,omitempty"`

	// Command The input to the graph.
	Command interface{} `json:"command,omitempty"`

	// Config The configuration for the assistant.
	Config *struct {
		Configurable   *map[string]interface{} `json:"configurable,omitempty"`
		RecursionLimit *int                    `json:"recursion_limit,omitempty"`
		Tags           *[]string               `json:"tags,omitempty"`
	} `json:"config,omitempty"`

	// Context Static context added to the assistant.
	Context *map[string]interface{} `json:"context,omitempty"`

	// Durability Durability level for the run. Must be one of 'sync', 'async', or 'exit'.
	Durability *RunCreateStatelessDurability `json:"durability,omitempty"`

	// FeedbackKeys Feedback keys to assign to run.
	FeedbackKeys *[]string `json:"feedback_keys,omitempty"`

	// Input The input to the graph.
	Input interface{} `json:"input,omitempty"`

	// InterruptAfter Nodes to interrupt immediately after they get executed.
	InterruptAfter interface{} `json:"interrupt_after,omitempty"`

	// InterruptBefore Nodes to interrupt immediately before they get executed.
	InterruptBefore interface{} `json:"interrupt_before,omitempty"`

	// Metadata Metadata to assign to the run.
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// OnCompletion Whether to delete or keep the thread created for a stateless run. Must be one of 'delete' or 'keep'.
	OnCompletion *RunCreateStatelessOnCompletion `json:"on_completion,omitempty"`

	// OnDisconnect The disconnect mode to use. Must be one of 'cancel' or 'continue'.
	OnDisconnect *RunCreateStatelessOnDisconnect `json:"on_disconnect,omitempty"`

	// StreamMode The stream mode(s) to use.
	StreamMode interface{} `json:"stream_mode,omitempty"`

	// StreamResumable Whether to persist the stream chunks in order to resume the stream later.
	StreamResumable *bool `json:"stream_resumable,omitempty"`

	// StreamSubgraphs Whether to stream output from subgraphs.
	StreamSubgraphs *bool `json:"stream_subgraphs,omitempty"`

	// Webhook Webhook to call after LangGraph API call is done.
	Webhook *string `json:"webhook,omitempty"`
}

// RunCreateStatelessDurability Durability level for the run. Must be one of 'sync', 'async', or 'exit'.
type RunCreateStatelessDurability string

// RunCreateStatelessOnCompletion Whether to delete or keep the thread created for a stateless run. Must be one of 'delete' or 'keep'.
type RunCreateStatelessOnCompletion string

// RunCreateStatelessOnDisconnect The disconnect mode to use. Must be one of 'cancel' or 'continue'.
type RunCreateStatelessOnDisconnect string

// RunsCancel Payload for cancelling runs.
type RunsCancel struct {
	// RunIds List of run IDs to cancel.
	RunIds *[]openapi_types.UUID `json:"run_ids,omitempty"`

	// Status Filter runs by status to cancel. Must be one of 'pending', 'running', or 'all'.
	Status *RunsCancelStatus `json:"status,omitempty"`

	// ThreadId The ID of the thread containing runs to cancel.
	ThreadId *openapi_types.UUID `json:"thread_id,omitempty"`
}

// RunsCancelStatus Filter runs by status to cancel. Must be one of 'pending', 'running', or 'all'.
type RunsCancelStatus string

// SearchItemsResponse defines model for SearchItemsResponse.
type SearchItemsResponse struct {
	Items []Item `json:"items"`
}

// Send A message to send to a node.
type Send struct {
	// Input The message to send.
	Input *map[string]interface{} `json:"input"`

	// Node The node to send the message to.
	Node string `json:"node"`
}

// StoreDeleteRequest Request to delete an item.
type StoreDeleteRequest struct {
	// Key The unique identifier for the item.
	Key string `json:"key"`

	// Namespace A list of strings representing the namespace path.
	Namespace *[]string `json:"namespace,omitempty"`
}

// StoreListNamespacesRequest defines model for StoreListNamespacesRequest.
type StoreListNamespacesRequest struct {
	// Limit Maximum number of namespaces to return (default is 100).
	Limit *int `json:"limit,omitempty"`

	// MaxDepth Optional integer specifying the maximum depth of namespaces to return.
	MaxDepth *int `json:"max_depth,omitempty"`

	// Offset Number of namespaces to skip before returning results (default is 0).
	Offset *int `json:"offset,omitempty"`

	// Prefix Optional list of strings representing the prefix to filter namespaces.
	Prefix *[]string `json:"prefix,omitempty"`

	// Suffix Optional list of strings representing the suffix to filter namespaces.
	Suffix *[]string `json:"suffix,omitempty"`
}

// StorePutRequest Request to store or update an item.
type StorePutRequest struct {
	// Key The unique identifier for the item within the namespace.
	Key string `json:"key"`

	// Namespace A list of strings representing the namespace path.
	Namespace []string `json:"namespace"`

	// Value A dictionary containing the item's data.
	Value map[string]interface{} `json:"value"`
}

// StoreSearchRequest Request to search for items within a namespace prefix.
type StoreSearchRequest struct {
	// Filter Optional dictionary of key-value pairs to filter results.
	Filter *map[string]interface{} `json:"filter,omitempty"`

	// Limit Maximum number of items to return (default is 10).
	Limit *int `json:"limit,omitempty"`

	// NamespacePrefix List of strings representing the namespace prefix.
	NamespacePrefix *[]string `json:"namespace_prefix,omitempty"`

	// Offset Number of items to skip before returning results (default is 0).
	Offset *int `json:"offset,omitempty"`

	// Query Query string for semantic/vector search.
	Query *string `json:"query,omitempty"`
}

// Subgraphs Map of graph name to graph schema metadata (`input_schema`, `output_schema`, `state_schema`, `config_schema`, `context_schema`).
type Subgraphs map[string]GraphSchemaNoId

// Thread defines model for Thread.
type Thread struct {
	// Config The thread config.
	Config *map[string]interface{} `json:"config,omitempty"`

	// CreatedAt The time the thread was created.
	CreatedAt time.Time `json:"created_at"`

	// Interrupts The current interrupts of the thread.
	Interrupts *map[string]interface{} `json:"interrupts,omitempty"`

	// Metadata The thread metadata.
	Metadata map[string]interface{} `json:"metadata"`

	// Status The status of the thread.
	Status ThreadStatus `json:"status"`

	// ThreadId The ID of the thread.
	ThreadId openapi_types.UUID `json:"thread_id"`

	// UpdatedAt The last time the thread was updated.
	UpdatedAt time.Time `json:"updated_at"`

	// Values The current state of the thread.
	Values *map[string]interface{} `json:"values,omitempty"`
}

// ThreadStatus The status of the thread.
type ThreadStatus string

// ThreadCountRequest Payload for counting threads.
type ThreadCountRequest struct {
	// Metadata Thread metadata to filter on.
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// Status Thread status to filter on.
	Status *ThreadCountRequestStatus `json:"status,omitempty"`

	// Values State values to filter on.
	Values *map[string]interface{} `json:"values,omitempty"`
}

// ThreadCountRequestStatus Thread status to filter on.
type ThreadCountRequestStatus string

// ThreadCreate Payload for creating a thread.
type ThreadCreate struct {
	// IfExists How to handle duplicate creation. Must be either 'raise' (raise error if duplicate), or 'do_nothing' (return existing thread).
	IfExists *ThreadCreateIfExists `json:"if_exists,omitempty"`

	// Metadata Metadata to add to thread.
	Metadata   *map[string]interface{} `json:"metadata,omitempty"`
	Supersteps *[]struct {
		Updates []ThreadSuperstepUpdate `json:"updates"`
	} `json:"supersteps,omitempty"`

	// ThreadId The ID of the thread. If not provided, a random UUID will be generated.
	ThreadId *openapi_types.UUID `json:"thread_id,omitempty"`

	// Ttl The time-to-live for the thread.
	Ttl *struct {
		// Strategy The TTL strategy. 'delete' removes the entire thread.
		Strategy *ThreadCreateTtlStrategy `json:"strategy,omitempty"`

		// Ttl The time-to-live in minutes from now until thread should be swept.
		Ttl *float32 `json:"ttl,omitempty"`
	} `json:"ttl,omitempty"`
}

// ThreadCreateIfExists How to handle duplicate creation. Must be either 'raise' (raise error if duplicate), or 'do_nothing' (return existing thread).
type ThreadCreateIfExists string

// ThreadCreateTtlStrategy The TTL strategy. 'delete' removes the entire thread.
type ThreadCreateTtlStrategy string

// ThreadPatch Payload for updating a thread.
type ThreadPatch struct {
	// Metadata Metadata to merge with existing thread metadata.
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// Ttl The time-to-live for the thread.
	Ttl *struct {
		// Strategy The TTL strategy. 'delete' removes the entire thread.
		Strategy *ThreadPatchTtlStrategy `json:"strategy,omitempty"`

		// Ttl The time-to-live in minutes from now until thread should be swept.
		Ttl *float32 `json:"ttl,omitempty"`
	} `json:"ttl,omitempty"`
}

// ThreadPatchTtlStrategy The TTL strategy. 'delete' removes the entire thread.
type ThreadPatchTtlStrategy string

// ThreadSearchRequest Payload for listing threads.
type ThreadSearchRequest struct {
	// Ids List of thread IDs to include. Others are excluded.
	Ids *[]openapi_types.UUID `json:"ids,omitempty"`

	// Limit Maximum number to return.
	Limit *int `json:"limit,omitempty"`

	// Metadata Thread metadata to filter on.
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// Offset Offset to start from.
	Offset *int `json:"offset,omitempty"`

	// Select Specify which fields to return. If not provided, all fields are returned.
	Select *[]ThreadSearchRequestSelect `json:"select,omitempty"`

	// SortBy Sort by field.
	SortBy *ThreadSearchRequestSortBy `json:"sort_by,omitempty"`

	// SortOrder Sort order.
	SortOrder *ThreadSearchRequestSortOrder `json:"sort_order,omitempty"`

	// Status Thread status to filter on.
	Status *ThreadSearchRequestStatus `json:"status,omitempty"`

	// Values State values to filter on.
	Values *map[string]interface{} `json:"values,omitempty"`
}

// ThreadSearchRequestSelect defines model for ThreadSearchRequest.Select.
type ThreadSearchRequestSelect string

// ThreadSearchRequestSortBy Sort by field.
type ThreadSearchRequestSortBy string

// ThreadSearchRequestSortOrder Sort order.
type ThreadSearchRequestSortOrder string

// ThreadSearchRequestStatus Thread status to filter on.
type ThreadSearchRequestStatus string

// ThreadState defines model for ThreadState.
type ThreadState struct {
	// Checkpoint Checkpoint config.
	Checkpoint       CheckpointConfig        `json:"checkpoint"`
	CreatedAt        string                  `json:"created_at"`
	Interrupts       *[]Interrupt            `json:"interrupts,omitempty"`
	Metadata         map[string]interface{}  `json:"metadata"`
	Next             []string                `json:"next"`
	ParentCheckpoint *map[string]interface{} `json:"parent_checkpoint,omitempty"`
	Tasks            *[]struct {
		// Checkpoint Checkpoint config.
		Checkpoint *CheckpointConfig `json:"checkpoint,omitempty"`
		Error      *string           `json:"error,omitempty"`
		Id         string            `json:"id"`
		Interrupts *[]Interrupt      `json:"interrupts,omitempty"`
		Name       string            `json:"name"`
		State      *ThreadState      `json:"state,omitempty"`
	} `json:"tasks,omitempty"`
	Values interface{} `json:"values"`
}

// ThreadStateCheckpointRequest Payload for getting the state of a thread at a checkpoint.
type ThreadStateCheckpointRequest struct {
	// Checkpoint Checkpoint config.
	Checkpoint CheckpointConfig `json:"checkpoint"`

	// Subgraphs Include subgraph states.
	Subgraphs *bool `json:"subgraphs,omitempty"`
}

// ThreadStateSearch defines model for ThreadStateSearch.
type ThreadStateSearch struct {
	// Before Checkpoint config.
	Before *CheckpointConfig `json:"before,omitempty"`

	// Checkpoint Checkpoint config.
	Checkpoint *CheckpointConfig `json:"checkpoint,omitempty"`

	// Limit The maximum number of states to return.
	Limit *int `json:"limit,omitempty"`

	// Metadata Filter states by metadata key-value pairs.
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
}

// ThreadStateUpdate Payload for updating the state of a thread.
type ThreadStateUpdate struct {
	// AsNode Update the state as if this node had just executed.
	AsNode *string `json:"as_node,omitempty"`

	// Checkpoint Checkpoint config.
	Checkpoint *CheckpointConfig `json:"checkpoint,omitempty"`

	// Values The values to update the state with.
	Values interface{} `json:"values,omitempty"`
}

// ThreadStateUpdateResponse Response for adding state to a thread.
type ThreadStateUpdateResponse struct {
	Checkpoint *map[string]interface{} `json:"checkpoint,omitempty"`
}

// ThreadSuperstepUpdate defines model for ThreadSuperstepUpdate.
type ThreadSuperstepUpdate struct {
	// AsNode Update the state as if this node had just executed.
	AsNode string `json:"as_node"`

	// Command The command associated with the update.
	Command interface{} `json:"command,omitempty"`
	Values  interface{} `json:"values,omitempty"`
}

// GetItemResponse Represents a single document or data entry in the graph's Store. Items are used to store cross-thread memories.
type GetItemResponse = Item

// ListNamespacesResponse defines model for ListNamespacesResponse.
type ListNamespacesResponse = ListNamespaceResponse

// PostA2aJSONBody defines parameters for PostA2a.
type PostA2aJSONBody struct {
	// Id Request identifier
	Id string `json:"id"`

	// Jsonrpc JSON-RPC version
	Jsonrpc PostA2aJSONBodyJsonrpc `json:"jsonrpc"`

	// Method The method to invoke
	Method PostA2aJSONBodyMethod `json:"method"`

	// Params Method parameters
	Params *map[string]interface{} `json:"params,omitempty"`
}

// PostA2aParams defines parameters for PostA2a.
type PostA2aParams struct {
	// Accept Must be application/json
	Accept PostA2aParamsAccept `json:"Accept"`
}

// PostA2aParamsAccept defines parameters for PostA2a.
type PostA2aParamsAccept string

// PostA2aJSONBodyJsonrpc defines parameters for PostA2a.
type PostA2aJSONBodyJsonrpc string

// PostA2aJSONBodyMethod defines parameters for PostA2a.
type PostA2aJSONBodyMethod string

// PostA2a200JSONResponseBodyJsonrpc defines parameters for PostA2a.
type PostA2a200JSONResponseBodyJsonrpc string

// GetAssistantGraphAssistantsAssistantIdGraphGetParams defines parameters for GetAssistantGraphAssistantsAssistantIdGraphGet.
type GetAssistantGraphAssistantsAssistantIdGraphGetParams struct {
	// Xray Include graph representation of subgraphs. If an integer value is provided, only subgraphs with a depth less than or equal to the value will be included.
	Xray interface{} `form:"xray,omitempty" json:"xray,omitempty"`
}

// SetLatestAssistantVersionAssistantsAssistantIdVersionsPostParams defines parameters for SetLatestAssistantVersionAssistantsAssistantIdVersionsPost.
type SetLatestAssistantVersionAssistantsAssistantIdVersionsPostParams struct {
	// Version The version to change to.
	Version int `form:"version" json:"version"`
}

// GetAssistantSubgraphsAssistantsAssistantIdSubgraphsGetParams defines parameters for GetAssistantSubgraphsAssistantsAssistantIdSubgraphsGet.
type GetAssistantSubgraphsAssistantsAssistantIdSubgraphsGetParams struct {
	// Recurse Recursively retrieve subgraphs of subgraphs.
	Recurse *bool `form:"recurse,omitempty" json:"recurse,omitempty"`
}

// GetAssistantSubgraphsAssistantsAssistantIdSubgraphsNamespaceGetParams defines parameters for GetAssistantSubgraphsAssistantsAssistantIdSubgraphsNamespaceGet.
type GetAssistantSubgraphsAssistantsAssistantIdSubgraphsNamespaceGetParams struct {
	// Recurse Recursively retrieve subgraphs of subgraphs.
	Recurse *bool `form:"recurse,omitempty" json:"recurse,omitempty"`
}

// PostMcpJSONBody defines parameters for PostMcp.
type PostMcpJSONBody = map[string]interface{}

// PostMcpParams defines parameters for PostMcp.
type PostMcpParams struct {
	// Accept Accept header must include both 'application/json' and 'text/event-stream' media types.
	Accept PostMcpParamsAccept `json:"Accept"`
}

// PostMcpParamsAccept defines parameters for PostMcp.
type PostMcpParamsAccept string

// SystemMetricsMetricsGetParams defines parameters for SystemMetricsMetricsGet.
type SystemMetricsMetricsGetParams struct {
	Format *SystemMetricsMetricsGetParamsFormat `form:"format,omitempty" json:"format,omitempty"`
}

// SystemMetricsMetricsGetParamsFormat defines parameters for SystemMetricsMetricsGet.
type SystemMetricsMetricsGetParamsFormat string

// HealthCheckOkGetParams defines parameters for HealthCheckOkGet.
type HealthCheckOkGetParams struct {
	CheckDb *HealthCheckOkGetParamsCheckDb `form:"check_db,omitempty" json:"check_db,omitempty"`
}

// HealthCheckOkGetParamsCheckDb defines parameters for HealthCheckOkGet.
type HealthCheckOkGetParamsCheckDb int

// HealthCheckOkGet200JSONResponseBodyOk defines parameters for HealthCheckOkGet.
type HealthCheckOkGet200JSONResponseBodyOk bool

// CancelRunsPostParams defines parameters for CancelRunsPost.
type CancelRunsPostParams struct {
	// Action Action to take when cancelling the run. Possible values are `interrupt` or `rollback`. `interrupt` will simply cancel the run. `rollback` will cancel the run and delete the run and associated checkpoints afterwards.
	Action *CancelRunsPostParamsAction `form:"action,omitempty" json:"action,omitempty"`
}

// CancelRunsPostParamsAction defines parameters for CancelRunsPost.
type CancelRunsPostParamsAction string

// GetItemParams defines parameters for GetItem.
type GetItemParams struct {
	Key       string    `form:"key" json:"key"`
	Namespace *[]string `form:"namespace,omitempty" json:"namespace,omitempty"`
}

// GetThreadHistoryThreadsThreadIdHistoryGetParams defines parameters for GetThreadHistoryThreadsThreadIdHistoryGet.
type GetThreadHistoryThreadsThreadIdHistoryGetParams struct {
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Before *string `form:"before,omitempty" json:"before,omitempty"`
}

// ListRunsHttpThreadsThreadIdRunsGetParams defines parameters for ListRunsHttpThreadsThreadIdRunsGet.
type ListRunsHttpThreadsThreadIdRunsGetParams struct {
	Limit  *int                                              `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int                                              `form:"offset,omitempty" json:"offset,omitempty"`
	Status *ListRunsHttpThreadsThreadIdRunsGetParamsStatus   `form:"status,omitempty" json:"status,omitempty"`
	Select *[]ListRunsHttpThreadsThreadIdRunsGetParamsSelect `form:"select,omitempty" json:"select,omitempty"`
}

// ListRunsHttpThreadsThreadIdRunsGetParamsStatus defines parameters for ListRunsHttpThreadsThreadIdRunsGet.
type ListRunsHttpThreadsThreadIdRunsGetParamsStatus string

// ListRunsHttpThreadsThreadIdRunsGetParamsSelect defines parameters for ListRunsHttpThreadsThreadIdRunsGet.
type ListRunsHttpThreadsThreadIdRunsGetParamsSelect string

// CancelRunHttpThreadsThreadIdRunsRunIdCancelPostParams defines parameters for CancelRunHttpThreadsThreadIdRunsRunIdCancelPost.
type CancelRunHttpThreadsThreadIdRunsRunIdCancelPostParams struct {
	Wait *bool `form:"wait,omitempty" json:"wait,omitempty"`

	// Action Action to take when cancelling the run. Possible values are `interrupt` or `rollback`. `interrupt` will simply cancel the run. `rollback` will cancel the run and delete the run and associated checkpoints afterwards.
	Action *CancelRunHttpThreadsThreadIdRunsRunIdCancelPostParamsAction `form:"action,omitempty" json:"action,omitempty"`
}

// CancelRunHttpThreadsThreadIdRunsRunIdCancelPostParamsAction defines parameters for CancelRunHttpThreadsThreadIdRunsRunIdCancelPost.
type CancelRunHttpThreadsThreadIdRunsRunIdCancelPostParamsAction string

// JoinRunHttpThreadsThreadIdRunsRunIdJoinGetParams defines parameters for JoinRunHttpThreadsThreadIdRunsRunIdJoinGet.
type JoinRunHttpThreadsThreadIdRunsRunIdJoinGetParams struct {
	CancelOnDisconnect *bool `form:"cancel_on_disconnect,omitempty" json:"cancel_on_disconnect,omitempty"`
}

// StreamRunHttpThreadsThreadIdRunsRunIdJoinGetParams defines parameters for StreamRunHttpThreadsThreadIdRunsRunIdJoinGet.
type StreamRunHttpThreadsThreadIdRunsRunIdJoinGetParams struct {
	StreamMode         *string `form:"stream_mode,omitempty" json:"stream_mode,omitempty"`
	CancelOnDisconnect *bool   `form:"cancel_on_disconnect,omitempty" json:"cancel_on_disconnect,omitempty"`
	LastEventID        *string `json:"Last-Event-ID,omitempty"`
}

// GetLatestThreadStateThreadsThreadIdStateGetParams defines parameters for GetLatestThreadStateThreadsThreadIdStateGet.
type GetLatestThreadStateThreadsThreadIdStateGetParams struct {
	// Subgraphs Whether to include subgraphs in the response.
	Subgraphs *bool `form:"subgraphs,omitempty" json:"subgraphs,omitempty"`
}

// PostThreadStateAtCheckpointThreadsThreadIdStateCheckpointIdGetParams defines parameters for PostThreadStateAtCheckpointThreadsThreadIdStateCheckpointIdGet.
type PostThreadStateAtCheckpointThreadsThreadIdStateCheckpointIdGetParams struct {
	Subgraphs *bool `form:"subgraphs,omitempty" json:"subgraphs,omitempty"`
}

// GetThreadStateAtCheckpointThreadsThreadIdStateCheckpointIdGetParams defines parameters for GetThreadStateAtCheckpointThreadsThreadIdStateCheckpointIdGet.
type GetThreadStateAtCheckpointThreadsThreadIdStateCheckpointIdGetParams struct {
	// Subgraphs Whether to include subgraphs in the response.
	Subgraphs *bool `form:"subgraphs,omitempty" json:"subgraphs,omitempty"`
}

// JoinThreadStreamThreadsThreadIdStreamGetParams defines parameters for JoinThreadStreamThreadsThreadIdStreamGet.
type JoinThreadStreamThreadsThreadIdStreamGetParams struct {
	StreamModes interface{} `form:"stream_modes,omitempty" json:"stream_modes,omitempty"`
	LastEventID *string     `json:"Last-Event-ID,omitempty"`
}

// PostA2aJSONRequestBody defines body for PostA2a for application/json ContentType.
type PostA2aJSONRequestBody PostA2aJSONBody

// CreateAssistantAssistantsPostJSONRequestBody defines body for CreateAssistantAssistantsPost for application/json ContentType.
type CreateAssistantAssistantsPostJSONRequestBody = AssistantCreate

// CountAssistantsAssistantsCountPostJSONRequestBody defines body for CountAssistantsAssistantsCountPost for application/json ContentType.
type CountAssistantsAssistantsCountPostJSONRequestBody = AssistantCountRequest

// SearchAssistantsAssistantsSearchPostJSONRequestBody defines body for SearchAssistantsAssistantsSearchPost for application/json ContentType.
type SearchAssistantsAssistantsSearchPostJSONRequestBody = AssistantSearchRequest

// PatchAssistantAssistantsAssistantIdPatchJSONRequestBody defines body for PatchAssistantAssistantsAssistantIdPatch for application/json ContentType.
type PatchAssistantAssistantsAssistantIdPatchJSONRequestBody = AssistantPatch

// PostMcpJSONRequestBody defines body for PostMcp for application/json ContentType.
type PostMcpJSONRequestBody = PostMcpJSONBody

// RunStatelessRunsPostJSONRequestBody defines body for RunStatelessRunsPost for application/json ContentType.
type RunStatelessRunsPostJSONRequestBody = RunCreateStateless

// RunBatchStatelessRunsPostJSONRequestBody defines body for RunBatchStatelessRunsPost for application/json ContentType.
type RunBatchStatelessRunsPostJSONRequestBody = RunBatchCreate

// CancelRunsPostJSONRequestBody defines body for CancelRunsPost for application/json ContentType.
type CancelRunsPostJSONRequestBody = RunsCancel

// CreateCronRunsCronsPostJSONRequestBody defines body for CreateCronRunsCronsPost for application/json ContentType.
type CreateCronRunsCronsPostJSONRequestBody = CronCreate

// CountCronsRunsCronsCountPostJSONRequestBody defines body for CountCronsRunsCronsCountPost for application/json ContentType.
type CountCronsRunsCronsCountPostJSONRequestBody = CronCountRequest

// SearchCronsRunsCronsPostJSONRequestBody defines body for SearchCronsRunsCronsPost for application/json ContentType.
type SearchCronsRunsCronsPostJSONRequestBody = CronSearch

// StreamRunStatelessRunsStreamPostJSONRequestBody defines body for StreamRunStatelessRunsStreamPost for application/json ContentType.
type StreamRunStatelessRunsStreamPostJSONRequestBody = RunCreateStateless

// WaitRunStatelessRunsWaitPostJSONRequestBody defines body for WaitRunStatelessRunsWaitPost for application/json ContentType.
type WaitRunStatelessRunsWaitPostJSONRequestBody = RunCreateStateless

// DeleteItemJSONRequestBody defines body for DeleteItem for application/json ContentType.
type DeleteItemJSONRequestBody = StoreDeleteRequest

// PutItemJSONRequestBody defines body for PutItem for application/json ContentType.
type PutItemJSONRequestBody = StorePutRequest

// SearchItemsJSONRequestBody defines body for SearchItems for application/json ContentType.
type SearchItemsJSONRequestBody = StoreSearchRequest

// ListNamespacesJSONRequestBody defines body for ListNamespaces for application/json ContentType.
type ListNamespacesJSONRequestBody = StoreListNamespacesRequest

// CreateThreadThreadsPostJSONRequestBody defines body for CreateThreadThreadsPost for application/json ContentType.
type CreateThreadThreadsPostJSONRequestBody = ThreadCreate

// CountThreadsThreadsCountPostJSONRequestBody defines body for CountThreadsThreadsCountPost for application/json ContentType.
type CountThreadsThreadsCountPostJSONRequestBody = ThreadCountRequest

// SearchThreadsThreadsSearchPostJSONRequestBody defines body for SearchThreadsThreadsSearchPost for application/json ContentType.
type SearchThreadsThreadsSearchPostJSONRequestBody = ThreadSearchRequest

// PatchThreadThreadsThreadIdPatchJSONRequestBody defines body for PatchThreadThreadsThreadIdPatch for application/json ContentType.
type PatchThreadThreadsThreadIdPatchJSONRequestBody = ThreadPatch

// GetThreadHistoryPostThreadsThreadIdHistoryPostJSONRequestBody defines body for GetThreadHistoryPostThreadsThreadIdHistoryPost for application/json ContentType.
type GetThreadHistoryPostThreadsThreadIdHistoryPostJSONRequestBody = ThreadStateSearch

// CreateRunThreadsThreadIdRunsPostJSONRequestBody defines body for CreateRunThreadsThreadIdRunsPost for application/json ContentType.
type CreateRunThreadsThreadIdRunsPostJSONRequestBody = RunCreateStateful

// CreateThreadCronThreadsThreadIdRunsCronsPostJSONRequestBody defines body for CreateThreadCronThreadsThreadIdRunsCronsPost for application/json ContentType.
type CreateThreadCronThreadsThreadIdRunsCronsPostJSONRequestBody = CronCreate

// StreamRunThreadsThreadIdRunsStreamPostJSONRequestBody defines body for StreamRunThreadsThreadIdRunsStreamPost for application/json ContentType.
type StreamRunThreadsThreadIdRunsStreamPostJSONRequestBody = RunCreateStateful

// WaitRunThreadsThreadIdRunsWaitPostJSONRequestBody defines body for WaitRunThreadsThreadIdRunsWaitPost for application/json ContentType.
type WaitRunThreadsThreadIdRunsWaitPostJSONRequestBody = RunCreateStateful

// UpdateThreadStateThreadsThreadIdStatePostJSONRequestBody defines body for UpdateThreadStateThreadsThreadIdStatePost for application/json ContentType.
type UpdateThreadStateThreadsThreadIdStatePostJSONRequestBody = ThreadStateUpdate

// PostThreadStateAtCheckpointThreadsThreadIdStateCheckpointIdGetJSONRequestBody defines body for PostThreadStateAtCheckpointThreadsThreadIdStateCheckpointIdGet for application/json ContentType.
type PostThreadStateAtCheckpointThreadsThreadIdStateCheckpointIdGetJSONRequestBody = ThreadStateCheckpointRequest
