-- Transactional-outbox query set.
-- Built from spec/models/d2/relay.d2 + outbox/transactional-outbox.yml.
--
-- These are the ONLY statements that touch events + outbox. The write-path
-- statements (AppendEvent / EnqueueOutbox / NotifyOutbox) are executed inside
-- a single Go-managed transaction per aggregate Save() — a rollback drops the
-- event, the outbox row, AND the wake-up notify together (Postgres makes the
-- NOTIFY visible to LISTENers only on commit). The drain-path statements
-- (FetchUnpublished / MarkPublished / MarkFailed / CleanupPublished) are run
-- by the outbox relay goroutine.
--
-- Annotated for sqlc (-- name: ... :kind) so the Go data layer can be
-- generated, but the SQL is plain parameterized pgx and works hand-written too.

-- ============================================================================
-- WRITE PATH — runs inside the same TX as the aggregate's state change.
-- ============================================================================

-- AppendEvent appends one immutable event. The increment_version_on_event
-- trigger advances event_streams.version. event_id is generated by the app so
-- the matching outbox row can carry the identical id for dedup.
-- name: AppendEvent :one
INSERT INTO events (
    event_id, stream_id, aggregate_type, aggregate_id,
    event_type, event_version, payload, metadata
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, occurred_at;

-- EnqueueOutbox mirrors the event into the outbox in the SAME TX.
-- ON CONFLICT (event_id) DO NOTHING keeps the write idempotent.
-- name: EnqueueOutbox :exec
INSERT INTO outbox (
    event_id, aggregate_type, aggregate_id, event_type, payload, metadata
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (event_id) DO NOTHING;

-- EnsureStream upserts the aggregate's stream row before its first event.
-- name: EnsureStream :one
INSERT INTO event_streams (stream_id, aggregate_type, aggregate_id, version)
VALUES ($1, $2, $3, 0)
ON CONFLICT (aggregate_type, aggregate_id) DO UPDATE
    SET updated_at = now()
RETURNING stream_id, version;

-- NotifyOutbox fires the wake-up signal. Empty payload — the relay re-queries
-- on wake-up rather than trusting the payload. One NOTIFY per Save() commit.
-- name: NotifyOutbox :exec
SELECT pg_notify('outbox_new', '');

-- ============================================================================
-- DRAIN PATH — runs in the outbox relay goroutine (main pool, not the LISTEN
-- connection).
-- ============================================================================

-- FetchUnpublished drains a FIFO batch of rows eligible to publish: never-
-- published AND (never retried OR past their backoff). Ordered by id.
-- name: FetchUnpublished :many
SELECT id, event_id, aggregate_type, aggregate_id, event_type, payload, metadata, attempts
FROM outbox
WHERE NOT published
  AND (next_retry_at IS NULL OR next_retry_at <= now())
ORDER BY id
LIMIT $1;

-- MarkPublished marks a row delivered after a successful JetStream publish.
-- name: MarkPublished :exec
UPDATE outbox
SET published = TRUE,
    published_at = now(),
    last_error = NULL
WHERE id = $1;

-- MarkFailed records a transient publish failure and schedules the next retry.
-- Backoff (2^attempts minutes, capped at 60) is computed by the relay and
-- passed in as $3 so this statement stays declarative.
-- name: MarkFailed :exec
UPDATE outbox
SET attempts = attempts + 1,
    last_error = $2,
    next_retry_at = $3
WHERE id = $1;

-- CleanupPublished prunes delivered rows older than the retention window.
-- Run periodically by the outbox cleanup worker.
-- name: CleanupPublished :execrows
DELETE FROM outbox
WHERE published = TRUE
  AND published_at < $1;
